<a href="https://colab.research.google.com/github/muralianamala/pythonlearning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# supports element-wise operation and vectorization

In [ ]:
arr = np.arange(1,5)
arr

array([1, 2, 3, 4])

In [ ]:
arr*2

array([2, 4, 6, 8])

In [ ]:
#faster execution speed

# **Initializing Array**

In [ ]:
#1. initializing array using python list
arr1 = np.array([1,2,3,4])
type(arr1)

numpy.ndarray

In [ ]:
#creates 2-D array of float datatype array
arr2 = np.array([[1,2,3,4],[2,3,4,5]],dtype="float")
type(arr2)
arr2

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [ ]:
#initializing numpy array by using arange
#step size can be float
arr3 = np.arange(10).reshape(2,5)
print(arr3.ndim)
print(arr3.shape)
print(arr3)
print(len(arr3))
row, col = arr3.shape
print(row, col)
arr4 = np.arange(2,5,0.5)
arr4

2
(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
2
2 5


array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
#Returns evenly spaced numbers over specified interval
print(np.linspace(0,100,5))
print(np.linspace(0,100,4))
print(np.linspace(0,10,5))
print(np.linspace(1,11,4))

[  0.  25.  50.  75. 100.]
[  0.          33.33333333  66.66666667 100.        ]
[ 0.   2.5  5.   7.5 10. ]
[ 1.          4.33333333  7.66666667 11.        ]


In [ ]:
np.linspace?

In [ ]:
#Creates an array with all elements 0
zer_arr = np.zeros(6)
zer_arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
#creates an array with all elements to 1
ones_arr = np.ones(6)
ones_arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
#Generates an array with elements belonging to continuous uniform distribution
np.random.rand(3,2)

array([[0.62965812, 0.72484013],
       [0.24756577, 0.57165282],
       [0.58384876, 0.97479013]])

## **Properties of an Array**

In [ ]:
#no of dimensions
arr.ndim

1

In [ ]:
#shape of an array
arr.shape

(4,)

In [ ]:
arr.dtype

dtype('int64')

## **Accessing Elements**

In [ ]:
# single-element indexing
print(arr1)
print(arr1[2])
print(arr1[3])

[1 2 3 4]
3
4


In [ ]:
arr = np.arange(1,10)
print(arr)
print(arr[[2,3]]) # multi indexing

[1 2 3 4 5 6 7 8 9]
[3 4]


In [ ]:
arr1 = np.arange(1,11).reshape(2,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr1[1,4]

10

In [ ]:
arr1 [[0,0],[1,4]] # arr[[rows][cols]] # multi indexing in 2-D

array([2, 5])

In [ ]:
#negative indexing
print(arr)
print(arr[-1])

[1 2 3 4 5 6 7 8 9]
9


## **SLICING**

In [ ]:
print(arr)
print(arr[:3])
print(arr[2:6])
print(arr[::2]) # odd
print(arr[1::2]) # even
print(arr[-4:-1])
print(arr[::-1]) # reverse an array

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[3 4 5 6]
[1 3 5 7 9]
[2 4 6 8]
[6 7 8]
[9 8 7 6 5 4 3 2 1]


In [ ]:
print(arr1)
print(arr1[:,1:])
print(arr1[:1,1:])

#Slicing returns view not a copy
#.view() -- shallow copy
#.copy() -- deep copy

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 2  3  4  5]
 [ 7  8  9 10]]
[[2 3 4 5]]


## **MASKING**

- Fancy Indexing

In [ ]:
# Indexing based on condition. Masking creates a copy of the array not the view
print(arr1)
print(arr1[0,1])
a = arr1[arr1>5]
arr1[0,1]=10
print(a)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
[ 6  7  8  9 10]
[[ 1 10  3  4  5]
 [ 6  7  8  9 10]]


## **Operations**

### **Arithmetic**

In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,1,2,2])


In [ ]:
print(a+b)
print(np.add(a,b))

[2 3 5 6]
[2 3 5 6]


In [ ]:
print(a-b)
print(np.subtract(a,b))

[0 1 1 2]
[0 1 1 2]


In [ ]:
print(a*b)
print(np.multiply(a,b))

[1 2 6 8]
[1 2 6 8]


In [ ]:
print(a/b)
print(np.divide(a,b))

[1.  2.  1.5 2. ]
[1.  2.  1.5 2. ]


### **Comparision**

In [ ]:
a==b

array([ True, False, False, False])

In [ ]:
a>=b

array([ True,  True,  True,  True])

In [ ]:
a<=b

array([ True, False, False, False])

In [ ]:
print(np.all(a==b))
print(np.any(a==b))
print(np.all(a>=b))
print(np.any(a>=b))

False
True
True
True


### **Matrix multiplication**

In [ ]:
mat1 = np.array([[2],[1]])
mat2 = np.array([[2,4]])

In [ ]:
mat1@mat2

array([[4, 8],
       [2, 4]])

In [ ]:
np.matmul(mat1,mat2)

array([[4, 8],
       [2, 4]])

In [ ]:
np.dot(mat1,mat2)

array([[4, 8],
       [2, 4]])

## **AXIS**

- axis = 0 --> vertical axis (column wise)
- axis = 1 --> horizontal axis (row wise)

## **BROAD CASTING**

- For each dimensions (going from right sied)
-- The size of each dimension should be same OR
-- The size of one dimension should be 1

- RULE1:  If two arrays differ in the number of dimensions, the
shape of one with fewer dimensions is padded with ones on
its leading( Left Side).

- RULE2 :  If the shape of two arrays does not match in any
dimensions, the array with shape equal to 1 is stretched to
match the other shape i.e. broadcasted.

- RULE3 :  If in any dimension the sizes disagree and neither
equal to 1 , then Error is raised.

In [ ]:
arr1 = np.array([[0],[1]])
arr2 = np.array([[10,10],[20,20]])
print(arr1.shape)
print(arr2.shape)
print(arr1)
print(arr2)
print(arr1+arr2)

(2, 1)
(2, 2)
[[0]
 [1]]
[[10 10]
 [20 20]]
[[10 10]
 [21 21]]


In [ ]:
a3 = np.array([[0,1]])
a4 = np.array([[10,10],[20,20]])
print(a3)
print(a4)
print(a3.shape)
print(a4.shape)
print(a3+a4)

[[0 1]]
[[10 10]
 [20 20]]
(1, 2)
(2, 2)
[[10 11]
 [20 21]]


In [ ]:
#EG 3
#a1 shape = (2,4)
# a2 shape = (4,4)
# a1 + a2 --> Error --> RULE3 - niether of dimension is 1

In [ ]:
# EG 4
# a1 shape = (5, 2, 3)
# a2 shape = (2, 1)

# a1 + a2 = (5, 2, 3) --> RULE1 + RULE2 applies

a1 = np.arange(1,31).reshape(5,2,3)
print(a1)
print(a1.shape)
a2 = np.arange(1,3).reshape(2,1)
print(a2)
print(a2.shape)
print(a1 + a2)
print((a1 + a2).shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]]]
(5, 2, 3)
[[1]
 [2]]
(2, 1)
[[[ 2  3  4]
  [ 6  7  8]]

 [[ 8  9 10]
  [12 13 14]]

 [[14 15 16]
  [18 19 20]]

 [[20 21 22]
  [24 25 26]]

 [[26 27 28]
  [30 31 32]]]
(5, 2, 3)


In [ ]:
a1 = np.arange(1,31).reshape(5,2,3)
print(a1)
print(a1.shape)
a2 = np.arange(1,3).reshape(1,2)
print(a2)
print(a2.shape)
# print(a1 + a2)
# print((a1 + a2).shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]]]
(5, 2, 3)
[[1 2]]
(1, 2)


## **ARRAY MANIPULATION**

### **RESHAPING**

In [ ]:
array3d = np.array([[[1,2] ],[[5,6]] ])
print(array3d, array3d.ndim, array3d.shape)

print(array3d.reshape(2,2))
print(array3d.reshape(2,-1))
print(array3d.reshape(-1,2))
print(array3d.flatten()) # returns 1-d copy of array  --> deep copy

[[[1 2]]

 [[5 6]]] 3 (2, 1, 2)
[[1 2]
 [5 6]]
[[1 2]
 [5 6]]
[[1 2]
 [5 6]]
[1 2 5 6]


In [ ]:
print(array3d.ravel()) # returns 1-d view of array --> shallow copy
# Shallow copy  --> Reshaping, slicing, assigning
# Deep copy --> masking, arithmatic operation

[1 2 5 6]


In [ ]:
print(array3d, array3d.shape)

[[[1 2]]

 [[5 6]]] (2, 1, 2)


In [ ]:

print(np.transpose(array3d, (2,1,0)))
print(array3d.T)
print(array3d.T.shape)

[[[1 5]]

 [[2 6]]]
[[[1 5]]

 [[2 6]]]
(2, 1, 2)


## **SORT**

In [ ]:
arr2 = np.arange(1,11).reshape(2,5)
print(arr2)
a= arr2.sort()
print(a)
np.sort(arr2.T)
print(np.sort(arr2, axis=0))
print(np.sort(arr2, axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
a = np.array([[23,4,43],
             [12,89,3],
             [69,420,0]])
print(a)
print(np.sort(a,axis=1)) # horizontally (row wise)
print(np.sort(a,axis=0)) # vertically (column wise)
print(np.argsort(a)) # default horizontally (row-wise)
print(np.argsort(a,axis=0))

[[ 23   4  43]
 [ 12  89   3]
 [ 69 420   0]]
[[  4  23  43]
 [  3  12  89]
 [  0  69 420]]
[[ 12   4   0]
 [ 23  89   3]
 [ 69 420  43]]
[[1 0 2]
 [2 0 1]
 [2 0 1]]
[[1 0 2]
 [0 1 1]
 [2 2 0]]


## **SPLITTING**

In [ ]:
#np.split() --> split array into multiple sub arrays

In [ ]:
np.vectorize?

In [ ]:
def mypolyval(p,x):
  _p = list(p)
  print(_p)
  res = _p.pop(0)
  print(res)
  print(_p)
  while _p:
    res = res*x + _p.pop(0)
    print(res)
  return res

vpolyval = np.vectorize(mypolyval, excluded=['p'])
vpolyval(p=[1,2,3],x=[0,1])

[1, 2, 3]
1
[2, 3]
2
3
[1, 2, 3]
1
[2, 3]
2
3
[1, 2, 3]
1
[2, 3]
3
6


array([3, 6])

In [ ]:
a = np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(np.split(a,2))
print(np.split(a,3))
print(np.split(a,[2]))
print(np.split(a, [2,3]))

[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4, 5, 6])]
[array([1, 2]), array([3]), array([4, 5, 6])]


In [ ]:
# hsplit - splits horizontally - column wise
b = np.arange(1,16).reshape(3,5)
print(b)
print(np.hsplit(b,[1,2]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[array([[ 1],
       [ 6],
       [11]]), array([[ 2],
       [ 7],
       [12]]), array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])]


In [ ]:
# vsplit --> splits vertically - row wise
print(b)
print(np.vsplit(b,[1,2]))
print(np.vsplit(b,[1]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]])]
[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])]


## **MERGING**

In [ ]:
# np.vstack() --> Stacks array vertically
a = np.arange(5)
b = np.arange(5,10)
print(a)
print(b)

[0 1 2 3 4]
[5 6 7 8 9]


In [ ]:
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr = np.arange(1,5)
print(arr)

print(np.hstack((arr,arr,arr)))
print(np.vstack((arr,arr,arr)))

[1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [ ]:
c = np.arange(2,12).reshape(2,5)
print(c)
d = np.arange(3,13).reshape(5,2)
print(d)

[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
[[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


## **CONCATENATE**

In [ ]:
# concatenate 2 or more arrays along the given axis
print(arr)
print(np.concatenate([arr,arr]))
print(np.concatenate([arr,arr], axis=0))

[1 2 3 4]
[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4]


In [ ]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(np.concatenate([a,b], axis = 0))
print(np.concatenate([a,b], axis = 1))



[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
print(np.argmin(a))
print(np.argmax(a))
print(np.argsort(a))

0
3
[[0 1]
 [0 1]]
