<a href="https://colab.research.google.com/github/muralianamala/pythonlearning/blob/main/Scalar_DAV1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Day1 -> Python libraries: Numpy, Pandas, Matplotlib, Seaborn
Day2 -> Probability and Statistics
Day3 -> Hypothesis testing
'''

# **Numpy**

- import numpy as np
- %timeit - to calculate the execution time
- np.array(list) - converts list into np array
- ndim - gives dimensions
- shape - size of array in all dimensions
- np.arange - will create an array with a range of values
- np arrays can store only same datatypes
- Lists are storing references, but arrays are storing actual values in memory
- np.array(a,dtype="dataype") - which creates an array with similar datatype
- .astype(datatype) - converts an array into datatype
- indexing is similar to lists
-

In [ ]:
import numpy as np

In [ ]:
# Numerical in python - numpy means
# Speed comparision
# Numpy is useful wherever numerical operations needed

In [ ]:
l = list(range(10000000))
len(l)

10000000

In [ ]:
%timeit [i**2 for i in l]

3.59 s ± 570 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
b = np.array(l)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#element-wise operation
#ndarray - n dimensional array

In [ ]:
%timeit b**2

27.1 ms ± 464 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
a = np.array((5,7,3,6))
print(a**2)

[25 49  9 36]


In [ ]:
%timeit a**2

563 ns ± 5.97 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
b.ndim

1

In [ ]:
len(b)

10000000

In [ ]:
# it tells me the whole shape of array, if its multi dimensional
b.shape

(10000000,)

In [ ]:
#numpy are arrays, which they can store only same datatypes
#Lists are storing as references in memory
# Arrays are storing actual elements in memory

In [ ]:
c = list(range(1,10))
type(c)
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
c= np.arange(1,10)
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
type(c)

numpy.ndarray

In [ ]:
# stepping count can be a float in numpy
c = np.arange(1,5,0.5)
print(c)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
len(c)

8

In [ ]:
a = [1,3,"MA"]
b = np.array(a)
print(b)
# converted everything to String , which same datatype

['1' '3' 'MA']


In [ ]:
a = [1,2,3,4]
b = np.array(a)
print(b)

[1 2 3 4]


In [ ]:
c = np.array(a, dtype="float")
print(c)

[1. 2. 3. 4.]


In [ ]:
a = [1,3,"MA"]
b = np.array(a,dtype="float")
print(b)

ValueError: ignored

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
a.ndim

1

In [ ]:
a.shape

(8,)

In [ ]:
b = a.astype("float")
print(b)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [ ]:
b= np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b= np.arange(1,12)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b= np.arange(1,12,2)
# start, end, stepcount
print(b)

[ 1  3  5  7  9 11]


In [ ]:
# indexing is same as list
b= np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b[3]
b[::-2]

array([11,  9,  7,  5,  3,  1])

In [ ]:
b[-1]

11

In [ ]:
b[-2]

10

In [ ]:
b[-4]

8

In [ ]:
b

[8, 7, 6]

In [ ]:
b[1:5]

array([1, 2, 3, 4])

In [ ]:
b[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b[:2:-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3])

In [ ]:
b[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
b[:10:-1]

array([11])

In [ ]:
b[-5:11:]

array([ 7,  8,  9, 10])

In [ ]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
arr[2:4] = 0
arr

array([0, 1, 0, 0, 4])

# **MULTIINDEXING**

- array[[,]]

In [ ]:
b = np.arange(1,15,2)
print(b)

[ 1  3  5  7  9 11 13]


In [ ]:
b[2]

5

In [ ]:
b[6]

13

In [ ]:
b[[2,6]]

array([ 5, 13])

In [ ]:
b[[5,2,4]]

array([11,  5,  9])

In [ ]:
a = np.arange(1,30,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
a[[5,7,10,11]]

array([11, 15, 21, 23])

# **Fancy Indexing -> Masking**

- Masking is an intersting concept in numpy
- we can filter the records using this
- element wise operator will apply to each an every value within the array
-

In [ ]:
a = np.array([6,9,3,5,7,2,8,1])


In [ ]:
# element-wise operator
a < 6

array([False, False,  True,  True, False,  True, False,  True])

In [ ]:
a [ a<6 ]

array([3, 5, 2, 1])

In [ ]:
# Fliter all the even elements from a, using fancy indexing
a[ a%2==0 ]

array([6, 2, 8])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
b[::-2]


[6, 8]

In [ ]:
a[3:] = b[::-2]
print(a)

[1, 2, 3, 6, 8]


In [ ]:
a[ a%2 != 0]

array([9, 3, 5, 7, 1])

# **NPS Case Study**

In [ ]:
#NPS - Net promoter score
# NPS = %promoters - %Detractors

In [ ]:
'''
%promoters = #of promoters/total users
'''

In [ ]:
score = np.loadtxt("survey.txt", dtype = "int")

In [ ]:
p_rating = score[score > 8]
print(p_rating)

In [ ]:
no_promoters = len(p_rating)
print(no_promoters)

In [ ]:
total = len(score)

In [ ]:
perc_promoters = no_promoters*100/total
print(perc_promoters)

In [ ]:
d_rating = score[score < 7]
no_detractors = len(d_rating)
print(no_detractors)

In [ ]:
perc_detractors = no_detractors*100/total

In [ ]:
nps = perc_promoters - perc_detractors

In [ ]:
nps= np.round(nps,2)

# **NPS CASE Study**

In [ ]:
import numpy as np

In [ ]:
data = np.loadtxt("survey.txt", dtype="int")
total = len(data)

In [ ]:
promoters = data[data>8]
promoters

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [ ]:
#no_promoters = promoters.size
no_promoters = len(promoters)
perc_promoters = (no_promoters * 100)/total
print(perc_promoters)

52.18508997429306


In [ ]:
destructors = data[ data<7]
destructors

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [ ]:
no_dest = len(destructors)
print(no_dest)

332


In [ ]:
perc_dest = (no_dest * 100)/total
perc_dest

28.449014567266495

In [ ]:
nps = perc_promoters - perc_dest
print(np.round(nps,2))

23.74


# **ASSIGNMENT**

In [ ]:
a = np.arange(21,72,2)
print(a)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


In [ ]:
b = np.arange(22,71,2)
print(b)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

b= arr.astype(float)
print(b)

[10. 20. 30. 40. 50.]


In [ ]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

[  5  -9  20  25   3  -5  16 -10  -8]


In [ ]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


In [ ]:
a = np.arange(5,35,3)
print(a)

[ 5  8 11 14 17 20 23 26 29 32]


In [ ]:
np.arange?

In [ ]:
import numpy as np

In [ ]:
x = [[0 1 2] [3 4 5] [6 7 8] [9 10 11]]

[3]


In [ ]:
print(True == 1)

True


# **DAY2**

Following are the topics we shall be covering in the upcoming class.

- Topic 1: Introduction
- Topic 2: Working with 2-D arrays (Matrices)
- Topic 3: Indexing and Slicing in 2D arrays
- Topic 4: Fancy Indexing on 2D arrays
- Topic 5: Aggregate Functions
- Topic 6: Logical Operations
- Topic 7: Logical Operations Contd
- Topic 8: Use Case- Fitbit data analysis
- Topic 9: Basic EDA
- Topic 10: Fitbit Solution
- Topic 11: Doubt Resolution

In [ ]:
import numpy as np

In [ ]:
a = np.array(range(16))

In [ ]:
a.shape

(16,)

In [ ]:
a.ndim

1

## **RESHAPE**

In [ ]:
b = a.reshape(8,2)

In [ ]:
print(b.shape)
print(a.shape)

(8, 2)
(16,)


In [ ]:
b.ndim

2

In [ ]:
#Reshape posisble only certain scenarios
# we can only reshape upto same numbers
c = a.reshape(4,5)
# 4,5 - 4*5 --> 20

ValueError: ignored

In [ ]:
d = a.reshape(8,-1)
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a = a.reshape(8,2)
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
a.ndim

2

In [ ]:
len(a)

8

In [ ]:
len(a[0])

2

## **Transpose of a Matrix**

- a[row,col]

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a[ a>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
b= a.T

In [ ]:
b.shape

(4, 3)

In [ ]:
# nXm --> after transpose --> mXn

In [ ]:
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[0][1]

2

In [ ]:
a[1][2]

6

In [ ]:
a[1,2]

6

In [ ]:
a[2,0]

7

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[2,2]

9

In [ ]:
# Multi indexing in 2d numpy arrays
a = np.array([100,200,300,400,500,600])
a.ndim

1

In [ ]:
a[[2,3]]

array([300, 400])

In [ ]:
a[[2,3,4,1,2,2]]

array([300, 400, 500, 200, 300, 300])

In [ ]:
# multi indexing in 2-D
a = np.arange(9).reshape(3,3)

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a[[2,1],[1,2]]

array([7, 5])

In [ ]:
a[[2,0],[1,1]]

array([7, 1])

In [ ]:
# Task
# use multi indexing in 2D
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a[ [0,1,2],[0,1,2]]

array([0, 4, 8])

In [ ]:
#slicing
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(a[:2,:]) # slicing over rows
print(a[:,:2]) # slicing over columns

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]
 [8 9]]


In [ ]:
a[:,2:3]

array([[ 2],
       [ 6],
       [10]])

In [ ]:
a[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
# Fancy indexing - Masking in 2D

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
a[ a < 6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
import numpy as np
a= np.arange(14).reshape(2,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [ ]:
a[[1,1],[0,2]]

array([7, 9])

## **Aggregate Function**

- SUM
- MIN
- MAX
- COUNT
- AVG

In [ ]:
a= np.arange(1,11)

In [ ]:
np.sum(a)

55

In [ ]:
np.mean(a)

5.5

In [ ]:
np.min(a)

1

In [ ]:
np.max(a)

10

In [ ]:
# Aggregate functions in 2D

In [ ]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 0 --> vertical (columns)
# 1 --> Horizontal (rows)
print(np.argmax(a,axis=0))
print(np.argmax(a,axis=1))
print(np.argmin(a,axis=0))
print(np.argmin(a,axis=1))

print(np.max(a,axis=0))
print(np.max(a,axis=1))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[2 2 2 2]
[3 3 3]
[0 0 0 0]
[0 0 0]
[ 8  9 10 11]
[ 3  7 11]
[0 1 2 3]
[0 4 8]


In [ ]:
# row-wise sum [6,22,38]
np.sum(a,axis=1)

array([ 6, 22, 38])

In [ ]:
#column-wise sum
np.sum(a,axis=0)

array([12, 15, 18, 21])

In [ ]:
np.mean(a,axis=1)

array([1.5, 5.5, 9.5])

In [ ]:
np.mean(a,axis=0)

array([4., 5., 6., 7.])

In [ ]:
np.max(a,axis=1)

array([ 3,  7, 11])

In [ ]:
np.max(a,axis=0)

array([ 8,  9, 10, 11])

In [ ]:
np.min(a,axis=1)

array([0, 4, 8])

In [ ]:
np.min(a,axis=0)

array([0, 1, 2, 3])

## **Logical Operations**

- np.all(logic) - it checks all within an array apply and logic
- np.any(logic) - OR logic

In [ ]:
a = np.array([5,7,2,8,1])
a

array([5, 7, 2, 8, 1])

In [ ]:
a < 3

array([False, False,  True, False,  True])

In [ ]:
a >3

array([ True,  True, False,  True, False])

In [ ]:
#np.all() and np.any()
np.all(a<3)

False

In [ ]:
np.any(a<3)

True

In [ ]:
a = np.array([0,2,3])
b = np.array([1,3,5])
a>=b

array([False, False, False])

In [ ]:
# if lengths are different, cant apply element-wise operation
print(a+b)

[1 5 8]


In [ ]:
arr = np.array([-3,4,27,34,-2,0,-45,-11,4,0])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [ ]:
arr [arr < 0] = -1
arr [arr > 0] = 1
arr

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [ ]:
# WHERE()
# np.where(condition,true(value),false(value)])

In [ ]:
arr = np.where(arr>0,-1,1)
arr

array([ 1, -1, -1, -1,  1,  1,  1,  1, -1,  1])

In [ ]:
arr = np.array([-3,4,27,34,-2,0,-45,-11,4,0])
print(np.where(arr))
# HW -- understand this

(array([0, 1, 2, 3, 4, 6, 7, 8]),)


In [ ]:
import numpy as np

In [ ]:
arr = 2 * np.arange(0,2,0.5)
print(arr)
if np.all(arr):
    print("condition satisfies")
else:
    print("condition doesn't satisfy")

[0. 1. 2. 3.]
condition doesn't satisfy


In [ ]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print(v[:,None])
print(x[:,None])
print((x/v[:,None])[1][1])

[[200]
 [300]
 [400]]
[[[200 200 200]]

 [[300 300 300]]

 [[400 400 400]]]
1.0


In [ ]:
p = np.array([[0], [10], [20]])
print(p.shape)
q = np.array([10, 11, 12])
print(q.shape)
print((p + q))
print((p + q)[1][1])

(3, 1)
(3,)
[[10 11 12]
 [20 21 22]
 [30 31 32]]
21


In [ ]:
a = np.array([[16, 5], [81, 6], [33, 1]])
a.shape
a.ndim
print(a.T)
b= a.T.reshape(2,3)
print(b)
print(b.flatten())
print(a.flatten())

[[16 81 33]
 [ 5  6  1]]
[[16 81 33]
 [ 5  6  1]]
[16 81 33  5  6  1]
[16  5 81  6 33  1]


In [ ]:
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


In [ ]:
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
b = a.T
print(b)
b[-2][-2]

[[34  8 77]
 [28 56 87]
 [55  3 19]]


56

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8])

b = np.all((a%2 == 0) & (a > 3))
print(b)

False


In [ ]:
a = np.array([[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]])
print(a)
b = a[1:4]
print(b)
c = b[:,len(b[0])-3:len(b[0])+1]
print(c)
print(c[::-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[13 14 15]
 [ 9 10 11]
 [ 5  6  7]]


In [ ]:
a = np.array([[3, 3, 8, 2, 2, 1, 3, 9, 2, 3], [7, 9, 9, 7, 2, 2, 2, 7, 0, 5], [5, 1, 1, 9, 4, 7, 0, 4, 4, 8], [1, 3, 7, 2, 1, 1, 2, 0, 4, 3], [6, 4, 4, 4, 2, 5, 7, 3, 9, 6]])
a.shape
print(a)
b = a[1:4]
print(b)
c = b[:,len(b[0])-3:len(b[0])+1]
print(c)
print(c[::-1])

[[3 3 8 2 2 1 3 9 2 3]
 [7 9 9 7 2 2 2 7 0 5]
 [5 1 1 9 4 7 0 4 4 8]
 [1 3 7 2 1 1 2 0 4 3]
 [6 4 4 4 2 5 7 3 9 6]]
[[7 9 9 7 2 2 2 7 0 5]
 [5 1 1 9 4 7 0 4 4 8]
 [1 3 7 2 1 1 2 0 4 3]]
[[7 0 5]
 [4 4 8]
 [0 4 3]]
[[0 4 3]
 [4 4 8]
 [7 0 5]]


In [ ]:
a = np.array([[6, 28], [8, 56], [7, 19]])
print(a.reshape(1,6))
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6 28  8 56  7 19]]
[[ 6  8  7 28 56 19]]


In [ ]:
a = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
b = a[::-1]
print(b)
print(b.T)

a = np.transpose(a[::-1])
print(a)

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [ ]:
a = np.array([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])
a
a[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## **CASE STUDY**

In [ ]:
# HW --> Try to compare the avg steps the user takes when mood is happy and when mood is Sad

In [ ]:
data = np.loadtxt("fit.txt", dtype="str")
data
data.ndim

2

In [ ]:
data.shape
len(data)
print(data)

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

In [ ]:
data_t = data.T
print(data_t)
print(data_t[0])

[['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
  '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
  '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
  '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
  '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
  '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
  '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
  '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
  '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
  '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
  '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
  '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
  '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
  '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
  '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2

In [ ]:
step_count = data_t[1]
print(step_count)

['5464' '6041' '25' '5461' '6915' '4545' '4340' '1230' '61' '1258' '3148'
 '4687' '4732' '3519' '1580' '2822' '181' '3158' '4383' '3881' '4037'
 '202' '292' '330' '2209' '4550' '4435' '4779' '1831' '2255' '539' '5464'
 '6041' '4068' '4683' '4033' '6314' '614' '3149' '4005' '4880' '4136'
 '705' '570' '269' '4275' '5999' '4421' '6930' '5195' '546' '493' '995'
 '1163' '6676' '3608' '774' '1421' '4064' '2725' '5934' '1867' '3721'
 '2374' '2909' '1648' '799' '7102' '3941' '7422' '437' '1231' '1696'
 '4921' '221' '6500' '3575' '4061' '651' '753' '518' '5537' '4108' '5376'
 '3066' '177' '36' '299' '1447' '2599' '702' '133' '153' '500' '2127'
 '2203']


In [ ]:
step_count = np.array(step_count, dtype="int")
print(step_count)

[5464 6041   25 5461 6915 4545 4340 1230   61 1258 3148 4687 4732 3519
 1580 2822  181 3158 4383 3881 4037  202  292  330 2209 4550 4435 4779
 1831 2255  539 5464 6041 4068 4683 4033 6314  614 3149 4005 4880 4136
  705  570  269 4275 5999 4421 6930 5195  546  493  995 1163 6676 3608
  774 1421 4064 2725 5934 1867 3721 2374 2909 1648  799 7102 3941 7422
  437 1231 1696 4921  221 6500 3575 4061  651  753  518 5537 4108 5376
 3066  177   36  299 1447 2599  702  133  153  500 2127 2203]


In [ ]:
mood = data_t[2]
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [ ]:
b = np.unique(mood)
print(b)

['Happy' 'Neutral' 'Sad']


In [ ]:
len(b)

3

In [ ]:
# average step counts for the mood "Happy"
avg_count_happy = np.mean(step_count[mood == "Happy"])
print(avg_count_happy)
happy_step_count = step_count[mood == "Happy"]
print(happy_step_count)

3392.725
[4732  330 4550 4435 4779 1831 2255  539 5464 4068 4683 4033 6314  614
 3149 4005 4880 4136  705  269 4275 5999 4421 6930 5195  546  493  995
 3608  774 1421 4064 2725 5934 1867 7422 5537 5376  153 2203]


In [ ]:
sad_step_count = step_count[mood == "Sad"]
print(sad_step_count)

[6041   25 5461 4545 4340 1230   61 1258 3148 4687 3519 1580 2822  181
 6676 3721 1648  799 1696  221 4061  651  753  518  177   36  299  702
  133]


In [ ]:
#give me step count either happy or nuetral
step_count_either_happy_nuetral = step_count[ (mood == "Happy") | (mood == "Nuetral")]
print(step_count_either_happy_nuetral)

[4732  330 4550 4435 4779 1831 2255  539 5464 4068 4683 4033 6314  614
 3149 4005 4880 4136  705  269 4275 5999 4421 6930 5195  546  493  995
 3608  774 1421 4064 2725 5934 1867 7422 5537 5376  153 2203]


In [ ]:
# Try to compare avg steps the user takes when the mood is Happy and Sad
happy_step_count = step_count[ mood == "Happy"]
sad_step_count = step_count[ mood == "Sad"]
avg_steps_happy = np.mean(happy_step_count)
print(avg_steps_happy)
avg_steps_sad = np.mean(sad_step_count)
print(avg_steps_sad)
print(avg_steps_happy > avg_steps_sad)

3392.725
2103.0689655172414
True


In [ ]:
# explore linspace()



In [ ]:
import numpy as np

In [ ]:
data = np.loadtxt("IPTSFIL_20130211101655_ITEMS.txt", delimiter="|", dtype="str")
data

array([['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', ''],
       ['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', ''],
       ['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', ''],
       ...,
       ['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', ''],
       ['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', ''],
       ['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', '']],
      dtype='<U25')

In [ ]:
data.ndim

2

In [ ]:
data.size

7872

In [ ]:
len(data[0])

492

In [ ]:
data.T

array([['R', 'R', 'R', ..., 'R', 'R', 'R'],
       ['IPTSFIL', 'IPTSFIL', 'IPTSFIL', ..., 'IPTSFIL', 'IPTSFIL',
        'IPTSFIL'],
       ['AA', 'AA', 'AA', ..., 'AA', 'AA', 'AA'],
       ...,
       ['', '', '', ..., '', '', ''],
       ['BLOUSES - ANTHRO.', 'BLOUSES - ANTHRO.', 'BLOUSES - ANTHRO.',
        ..., 'BLOUSES - ANTHRO.', 'BLOUSES - ANTHRO.',
        'BLOUSES - ANTHRO.'],
       ['', '', '', ..., '', '', '']], dtype='<U25')

In [ ]:
import numpy as np

# **DAY-3**

Following are the topics we shall be covering in the upcoming class.

- Topic 1: Sorting (np.sort(ar,axis=(0,1)), argsort - will display index values of sorted order)
- Topic 2: Element-Wise Multiplication (will multiple on element-wise)
- Topic 3: Matrix multiplication. (np.dot(a,b),a@b,np.matmul(a.b)
- Topic 4: Vectorization (will call funtion by sending array)
- Topic 5: Broadcasting
- Topic 6: Quiz-4 Explanation
- Topic 7: Quiz-5 Explanation
- Topic 8: Doubt Resolution

In [ ]:
a = np.array([[23,4,43],
             [12,89,3],
             [69,420,0]])
b = np.sort(a)
b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [ ]:
b = np.sort(a, axis=1)
b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [ ]:
b = np.sort(a,axis=0)
b

array([[ 12,   4,   0],
       [ 23,  89,   3],
       [ 69, 420,  43]])

In [ ]:
#element-wise operations
a = np.arange(5)
b = np.arange(5)
#b = np.ones(5)
print(a)
print(b)

[0 1 2 3 4]
[0 1 2 3 4]


In [ ]:
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
a*b

array([ 0,  1,  4,  9, 16])

In [ ]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
b = np.arange(2,14).reshape(3,4)
print(b)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [ ]:
b.shape

(3, 4)

In [ ]:
print(a+b)

[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]]


In [ ]:
a*b

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [ ]:
#c1=r2
#r1Xc2

In [ ]:
'''
Matrix multiplication
1. np.dot
2. @ operater
3. mp.amtmul
'''

In [ ]:
a = np.arange(1,13).reshape(3,4)
b= np.arange(2,14).reshape(4,3)

In [ ]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [ ]:
#way1
c= np.dot(a,b)
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [ ]:
#way2
c= a@b
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [ ]:
#way3
c = np.matmul(a,b)
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [ ]:
a = np.arange(5)
b= np.arange(1,6)
print(a)
print(b)
print(a.shape)
print(b.shape)

[0 1 2 3 4]
[1 2 3 4 5]
(5,)
(5,)


In [ ]:
c = np.dot(a,b)
print(c)
#HW --> understand what exactly happend

40


In [ ]:
#vectorization
#Vectorization in NumPy refers to performing operations on entire arrays or array elements simultaneously, which is significantly faster and more efficient than using explicit loops.


# **vectorization**

- Vectorization in NumPy refers to performing operations on entire arrays or array elements simultaneously, which is significantly faster and more efficient than using explicit loops.


In [ ]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [ ]:
def solve(n):
  if n%2 ==0:
    n+=2
  else:
    n-=2
  return n


solve(10)

12

In [ ]:
solve(3)

1

In [ ]:
solve(7)

5

In [ ]:
#function called on each and every field within an array
#by calling function
new_solve = np.vectorize(solve)
print(new_solve(a))

[ 2 -1  4  1  6  3  8  5 10]


# **Broadcasting**

- ntile(array,(m,n))


In [ ]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [ ]:
#np.tile
c = np.tile(a,(3,1))
c

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
b = np.tile(a,(3,2))
b

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [ ]:
b.shape

(3, 8)

In [ ]:
a = np.arange(0,40,10)
a = np.tile(a,(3,1))
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
a.T

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
b = np.arange(3)
b

array([0, 1, 2])

In [ ]:
b = np.tile(b,(4,1))
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
a+b

ValueError: ignored

In [ ]:
#case3


In [ ]:
a= np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [ ]:
a = a.reshape(4,1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
a.shape

(4, 1)

In [ ]:
b = np.arange(0,3)
b

array([0, 1, 2])

In [ ]:
b.shape

(3,)

In [ ]:
print(a+b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
'''
Explanation
(4,1)
(1,3)
rule1 --> match the number either in row or columns
rule2 --> any one have 1

(4,3)

#case 2
a --> (4,3)
b --> (1,3)

c --> (4,3)
'''

In [ ]:
a = np.arange(8).reshape(2,4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
b = np.arange(16).reshape(4,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
import numpy as np
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
arr = np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]]) #(4,4)
arr

array([[ 2,  3,  4,  5],
       [ 1,  7,  3,  5],
       [ 2,  8,  6,  9],
       [11, 23, 12, 19]])

In [ ]:
arr1 = np.array([[2,2,2,2]]) #(1,4)
def func(x,y):
  return x*y
vec = np.vectorize(func)
print(vec(arr,arr1))

[[ 4  6  8 10]
 [ 2 14  6 10]
 [ 4 16 12 18]
 [22 46 24 38]]


In [ ]:
arr1 = np.array([[2],[2],[2],[2]]) #(4,1)
def func(x, y):
    return x * y
vec = np.vectorize(func)
print(vec(arr, arr1))

[[ 4  6  8 10]
 [ 2 14  6 10]
 [ 4 16 12 18]
 [22 46 24 38]]


In [ ]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
print(vec(arr, arr1))

[[ 4  6  8 10]
 [ 2 14  6 10]
 [ 4 16 12 18]
 [22 46 24 38]]


In [ ]:
def specific_elements(mat1,mat2,r1,r2,c1,c2):
  if (len(mat1[0]) != len(mat2)):
    result = -1
    return result
  matmul_array = np.matmul(mat1,mat2)
  print(matmul_array)
  result = matmul_array[r1:r2,c1:c2]
  return result

#mat1 = np.array([[6,6,4,7,9],[0,2,2,9,3],[6,0,2,5,2],[2,4,3,5,5]])
mat1 = np.array([[6,4,7,9],[2,2,9,3],[0,2,5,2],[4,3,5,5]])
mat2 = np.array([[8,6,6,8,3],[2,7,0,3,1],[3,2,1,5,2],[7,0,7,6,8],[1,5,6,4,5]])

print(specific_elements(mat1,mat2,1,3,2,4))

-1


In [ ]:
def sort_birds(birds,age):
  '''
  INPUT: birds, age -> 1D numpy array

  OUTPUT: result -> sorted bird 1D array
  '''

  ## STEP 1 : Get the sorted index of age.

  sorted_age_index = np.argsort(age)
  print(sorted_age_index)
  ## STEP 2: Use the index from previous step to get sorted birds

  result = birds[sorted_age_index]

  return result

In [ ]:
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])
print(sort_birds(birds,age))

[3 7 4 2 6 5 0 8 1 9]
['plovers' 'plovers' 'plovers' 'plovers' 'plovers' 'Cranes' 'spoonbills'
 'Cranes' 'plovers' 'spoonbills']


In [ ]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [ ]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [ ]:
import numpy as np

def calculate_mean_age(birds, age):
    '''
    INPUT: birds, age -> 1D array

    OUPUT: mean_age -> float variable
    '''

    mean_age = None

    ## STEP1. Create mask to get Crane birds from birds array
    mask = (birds == 'Cranes')

    ## STEP2. Get the age of crane birds

    crane_ages = age[mask]
    print(crane_ages)

    ## STEP 3. Calculate mean age of crane birds

    mean_age = ''

    ## STEP 4. Round off the mean age to 2 decimal points

    mean_age = ''



    return mean_age

In [ ]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

birds= np.array(birds)
age = np.array(age)

age = age[birds == 'Cranes']
mean_age = np.round(np.mean(age),2)
print(age)
print(mean_age)
#calculate_mean_age(birds,age)

[4.  5.5]
4.75


In [ ]:
birds = np.array(['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock'])
age = np.array([6, 1, 6, 5, 7, 6, 0, 9, 0, 7])
max_age = np.argmax(age)
print(max_age)
print(birds[max_age])

7
parrot


In [ ]:
arr1 = np.array([1,2,3,6,3,2])
arr2 = np.array([4,2,1,3,3,2])
arr3 = np.zeros(len(arr1))

In [ ]:
for i in range(len(arr1)):
    arr3[i] = arr1[i] * arr2[i]
print(arr3)

[ 4.  4.  3. 18.  9.  4.]


In [ ]:
arr3= arr2 * arr1
print(arr3)

[ 4  4  3 18  9  4]


In [ ]:
for i in range(len(arr1)):
    if(arr1[i] < 0 ):
        arr1[i] = -1
    else:
        arr1[i] = 1

print(arr1)

[1 1 1 1 1 1]


In [ ]:
arr1 = np.array([1,2,3]) # 1,3
arr2 = np.array([9,8,7]) # 1,3
np.dot(arr1, arr2)

46

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [ ]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [ ]:
arr1 = np.array([[1,2], [3,4]])
print(arr1.shape)
arr2 = np.array([1,1])
print(arr2.shape)
c = arr1@arr2
print(c)

(2, 2)
(2,)
[3 7]


In [ ]:
A = np.arange(9).reshape(3,3)
print(A)
print(A[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [ ]:
arr = [a+" "+b for a in [ 'Hello', 'Good'] for b in ['Dear', 'Bye']]
print(arr)

['Hello Dear', 'Hello Bye', 'Good Dear', 'Good Bye']


In [ ]:
a = [1,2,3,4,5,6,7,8,9]
b = [i for i in a if i>6]
print(b)

[7, 8, 9]


In [ ]:
a=[1,2,3,4]
b =[4,5,6,7]
c = [i*j for i in a for j in b]
print(c)

[4, 5, 6, 7, 8, 10, 12, 14, 12, 15, 18, 21, 16, 20, 24, 28]


In [ ]:
arr = [[1,2,3],[10,11,12],[4,5,6],[13,14,15],[10,1,2]]

print(max (arr, key=sum ) )
print(max(arr))

[13, 14, 15]
[13, 14, 15]


In [ ]:
list1 = ['Apple', 'Berry', 'Cherry', 'Papaya']
list2 = list1
list3 = list1[:]

list2[0] = 'Guava'
list3[1] = 'Kiwi'
print(list1)
print(list2)
print(list3)
total = 0
s = (list1,list2,list3)
print(s)
for ls in (list1, list2, list3):
  if ls[0] == 'Guava':
    total += 1

  if ls[1] == 'Kiwi':
    total += 20

print (total, list3[0])

['Guava', 'Berry', 'Cherry', 'Papaya']
['Guava', 'Berry', 'Cherry', 'Papaya']
['Apple', 'Kiwi', 'Cherry', 'Papaya']
(['Guava', 'Berry', 'Cherry', 'Papaya'], ['Guava', 'Berry', 'Cherry', 'Papaya'], ['Apple', 'Kiwi', 'Cherry', 'Papaya'])
22 Apple


In [ ]:
Menu = [['Sweet_Corn_Soup', 300.0], ['Cream_of_Tomato_Soup', 100.0], ['Bacon_and_Cheese', 150.0], ['Honey_Mustard', 230.0], ['Hot_Coffee', 50.0], ['Cold_Coffee', 50.0], ['Egg_Sandwiches', 130.0], ['Tacos', 400.0]]
print(Menu)

[['Sweet_Corn_Soup', 300.0], ['Cream_of_Tomato_Soup', 100.0], ['Bacon_and_Cheese', 150.0], ['Honey_Mustard', 230.0], ['Hot_Coffee', 50.0], ['Cold_Coffee', 50.0], ['Egg_Sandwiches', 130.0], ['Tacos', 400.0]]


In [ ]:
item_list =["Hot_Coffee","Cold_Coffee","Tacos"]

for i in range(len(Menu)):
  print(Menu[i][0])
  for j in item_list:
    if j == Menu[i][0]:
      print(Menu[i][0], Menu[i][1])
      Menu[i][1] = round(1.1 * Menu[i][1])
      print(Menu[i][1])
    else:
      continue
  i += 1
print(Menu)

Sweet_Corn_Soup
Cream_of_Tomato_Soup
Bacon_and_Cheese
Honey_Mustard
Hot_Coffee
Hot_Coffee 50.0
55
Cold_Coffee
Cold_Coffee 50.0
55
Egg_Sandwiches
Tacos
Tacos 400.0
440
[['Sweet_Corn_Soup', 300.0], ['Cream_of_Tomato_Soup', 100.0], ['Bacon_and_Cheese', 150.0], ['Honey_Mustard', 230.0], ['Hot_Coffee', 55], ['Cold_Coffee', 55], ['Egg_Sandwiches', 130.0], ['Tacos', 440]]


# **DAY4**

Following are the topics we shall be covering in the upcoming class.

- Topic 1: Views vs Copies (Shallow vs Deep Copy)
- Topic 2: Checking memory sharing using `np.shares_memory()`
- Topic 3: Understanding `.view()`
- Topic 4: Making Deep Cody using `.copy()`
- Topic 5: Array Splitting
- Topic 6: Understanding horizontal and vertical split
- Topic 7: Stacking (`vtack`)
- Topic 8: Stacking (`htack`)
- Topic 9: Understanding `np.concatenate()`
- Topic 10: Quiz-4 Explanation
- Topic 11: Doubt Resolution

In [ ]:
# Shallow copy
# Deep copy

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = a.reshape(2,2)
print(b)

[[0 1]
 [2 3]]


In [ ]:
a[0] = 11

In [ ]:
print(a)
print(b)

[11  1  2  3]
[[11  1]
 [ 2  3]]


In [ ]:
np.shares_memory(a,b) # Shallow copy

True

In [ ]:
c = a #shallow copy

In [ ]:
print(c)

[11  1  2  3]


In [ ]:
a[1]=15

In [ ]:
print(c)

[11 15  2  3]


In [ ]:
np.shares_memory(a,c)

True

In [ ]:
#eg 3
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = a[::2] # slicing --> shallow copy
b

array([1, 3, 5, 7, 9])

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
a[0] = 90
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b

array([90,  3,  5,  7,  9])

In [ ]:
a[1] = 70
print(a)
print(b)

[90 70  3  4  5  6  7  8  9 10]
[90  3  5  7  9]


Slicing creates a shallow copy

In [ ]:
a = np.arange(1,6)
print(a)

[1 2 3 4 5]


In [ ]:
b = a[a%2 == 0]
b

array([2, 4])

In [ ]:
np.shares_memory(a,b) # deep copy

False

a and b are not sharing same memory, this concept called deep copy

In [ ]:
a[1] = 100
a

array([  1, 100,   3,   4,   5])

In [ ]:
b

array([2, 4])

In [ ]:
# Shallow copy  --> Reshaping, slicing, assigning
# Deep copy --> masking, arithmatic operation

In [ ]:
#.view() --> Shallow copy

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a.view()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[3] = 100
b

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
#deep copy
#.copy()

In [ ]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [ ]:
#b = np.copy(a)
b = a.copy()
b

array([1, 2, 3, 4, 5])

In [ ]:
a[1]=100
b

array([1, 2, 3, 4, 5])

In [ ]:
np.shares_memory(a,b)

False

In [ ]:
#version2
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.split(a,2)
print(b)
d = np.split(a,5)
print(d)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [ ]:
c = np.split(a, [3,5,6])
c

[array([1, 2, 3]), array([4, 5]), array([6]), array([ 7,  8,  9, 10])]

In [ ]:
e = np.split(a,[3,6,9])
e

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10])]

In [ ]:
a = np.arange(2,15)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
b = np.split(a,[3,6,10])
b

[array([2, 3, 4]),
 array([5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14])]

In [ ]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.split(a,[2,4,7,8])
b

[array([1, 2]), array([3, 4]), array([5, 6, 7]), array([8]), array([ 9, 10])]

## **SPLIT in 2D**

- hsplit -- horizontal
- vsplit -- vertical

In [ ]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#hsplit -- split the horizontal axis -- column-wise split
b = np.hsplit(a,2)
b

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
b = np.hsplit(a,[1,2])
b

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
c = np.vsplit(a,2)
c

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
c = np.vsplit(a,[1,2])
c

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
c = np.vsplit(a,[2,3])
c

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

## **CONCATENATION**

In [ ]:
a = np.array([[2,4]])
a.ndim
a.shape

(1, 2)

In [ ]:
b = np.concatenate([a,a], axis=0)
print(b)

[[2 4]
 [2 4]]


In [ ]:
c = np.concatenate([a,a], axis=1)
print(c)
c.shape

[[2 4 2 4]]


(1, 4)

In [ ]:
#stacking
#hstack
#vstack


In [ ]:
a = np.array([[2,4,3]])
a

array([[2, 4, 3]])

In [ ]:
b = np.array([[5,4]])
b

array([[5, 4]])

In [ ]:
c = np.concatenate([a,b], axis=1)
c

array([[2, 4, 3, 5, 4]])

In [ ]:
a = np.arange(5)
b = np.arange(5,10)
print(a)
print(b)

[0 1 2 3 4]
[5 6 7 8 9]


In [ ]:
c = np.hstack((a,b))
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
d = np.vstack((b,a))
d

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [ ]:
a = np.array([[1],[2],[3]])
print(a.shape)
b = np.array([[4],[5],[6]])
print(b.shape)
c = np.vstack((a,b))
print(c)
print(c.shape)
d = np.hstack((a,b))
d

(3, 1)
(3, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


array([[1, 4],
       [2, 5],
       [3, 6]])