<a href="https://colab.research.google.com/github/muralianamala/pythonlearning/blob/main/Scalar_DAV1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Day1 -> Python libraries: Numpy, Pandas, Matplotlib, Seaborn
Day2 -> Probability and Statistics
Day3 -> Hypothesis testing
'''

# **Numpy**

In [ ]:
import numpy as np

In [ ]:
# Numerical in python - numpy means
# Speed comparision
# Numpy is useful wherever numerical operations needed

In [ ]:
l = list(range(10000000))
len(l)

10000000

In [ ]:
%timeit [i**2 for i in l]

3.59 s ± 570 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
b = np.array(l)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#element-wise operation
#ndarray - n dimensional array

In [ ]:
%timeit b**2

27.1 ms ± 464 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
a = np.array((5,7,3,6))
print(a**2)

[25 49  9 36]


In [ ]:
%timeit a**2

563 ns ± 5.97 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
b.ndim

1

In [ ]:
len(b)

10000000

In [ ]:
# it tells me the whole shape of array, if its multi dimensional
b.shape

(10000000,)

In [ ]:
#numpy are arrays, which they can store only same datatypes
#Lists are storing as references in memory
# Arrays are storing actual elements in memory

In [ ]:
c = list(range(1,10))
type(c)
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
c= np.arange(1,10)
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
type(c)

numpy.ndarray

In [ ]:
# stepping count can be a float in numpy
c = np.arange(1,5,0.5)
print(c)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
len(c)

8

In [ ]:
a = [1,3,"MA"]
b = np.array(a)
print(b)
# converted everything to String , which same datatype

['1' '3' 'MA']


In [ ]:
a = [1,2,3,4]
b = np.array(a)
print(b)

[1 2 3 4]


In [ ]:
c = np.array(a, dtype="float")
print(c)

[1. 2. 3. 4.]


In [ ]:
a = [1,3,"MA"]
b = np.array(a,dtype="float")
print(b)

ValueError: ignored

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
a.ndim

1

In [ ]:
a.shape

(8,)

In [ ]:
b = a.astype("float")
print(b)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [ ]:
b= np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b= np.arange(1,12)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b= np.arange(1,12,2)
print(b)

[ 1  3  5  7  9 11]


In [ ]:
# indexing is same as list
b= np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b[3]
b[::-2]

array([11,  9,  7,  5,  3,  1])

In [ ]:
b[-1]

11

In [ ]:
b[-2]

10

In [ ]:
b[-4]

8

In [ ]:
b

[8, 7, 6]

In [ ]:
b[1:5]

array([1, 2, 3, 4])

In [ ]:
b[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b[:2:-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3])

In [ ]:
b[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
b[:10:-1]

array([11])

In [ ]:
b[-5:11:]

array([ 7,  8,  9, 10])

In [ ]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
arr[2:4] = 0
arr

array([0, 1, 0, 0, 4])

# **MULTIINDEXING**

In [ ]:
b = np.arange(1,15,2)
print(b)

[ 1  3  5  7  9 11 13]


In [ ]:
b[2]

5

In [ ]:
b[6]

13

In [ ]:
b[[2,6]]

array([ 5, 13])

In [ ]:
b[[5,2,4]]

array([11,  5,  9])

# **Fancy Indexing -> Masking**

In [ ]:
a = np.array([6,9,3,5,7,2,8,1])


In [ ]:
# element-wise operator
a < 6

array([False, False,  True,  True, False,  True, False,  True])

In [ ]:
a [ a<6 ]

array([3, 5, 2, 1])

In [ ]:
# Fliter all the even elements from a, using fancy indexing
a[ a%2==0 ]

array([6, 2, 8])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
b[::-2]

[6, 8]

In [ ]:
a[3:] = b[::-2]
print(a)

[1, 2, 3, 6, 8]


In [ ]:
a[ a%2 != 0]

array([9, 3, 5, 7, 1])

# **NPS Case Study**

In [ ]:
#NPS - Net promoter score
# NPS = %promoters - %Detractors

In [ ]:
'''
%promoters = #of promoters/total users
'''

In [ ]:
score = np.loadtxt("survey.txt", dtype = "int")

In [ ]:
p_rating = score[score > 8]
print(p_rating)

In [ ]:
no_promoters = len(p_rating)
print(no_promoters)

In [ ]:
total = len(score)

In [ ]:
perc_promoters = no_promoters*100/total
print(perc_promoters)

In [ ]:
d_rating = score[score < 7]
no_detractors = len(d_rating)
print(no_detractors)

In [ ]:
perc_detractors = no_detractors*100/total

In [ ]:
nps = perc_promoters - perc_detractors

In [ ]:
nps= np.round(nps,2)

# **NPS CASE Study**

In [1]:
import numpy as np

In [7]:
data = np.loadtxt("survey.txt", dtype="int")
total = len(data)

In [5]:
promoters = data[data>8]
promoters

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [8]:
#no_promoters = promoters.size
no_promoters = len(promoters)
perc_promoters = (no_promoters * 100)/total
print(perc_promoters)

52.18508997429306


In [9]:
destructors = data[ data<7]
destructors

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [10]:
no_dest = len(destructors)
print(no_dest)

332


In [11]:
perc_dest = (no_dest * 100)/total
perc_dest

28.449014567266495

In [12]:
nps = perc_promoters - perc_dest
print(np.round(nps,2))

23.74
