<a href="https://colab.research.google.com/github/muralianamala/pythonlearning/blob/main/Scalar_DAV1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Day1 -> Python libraries: Numpy, Pandas, Matplotlib, Seaborn
Day2 -> Probability and Statistics
Day3 -> Hypothesis testing
'''

**Numpy**

In [1]:
import numpy as np

In [ ]:
# Numerical in python - numpy means
# Speed comparision
# Numpy is useful wherever numerical operations needed

In [2]:
l = list(range(10000000))
len(l)

10000000

In [4]:
%timeit [i**2 for i in l]

3.59 s ± 570 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
b = np.array(l)

In [6]:
type(b)

numpy.ndarray

In [ ]:
#element-wise operation
#ndarray - n dimensional array

In [7]:
%timeit b**2

27.1 ms ± 464 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
a = np.array((5,7,3,6))
print(a**2)

[25 49  9 36]


In [9]:
%timeit a**2

563 ns ± 5.97 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [10]:
b.ndim

1

In [11]:
len(b)

10000000

In [12]:
# it tells me the whole shape of array, if its multi dimensional
b.shape

(10000000,)

In [ ]:
#numpy are arrays, which they can store only same datatypes
#Lists are storing as references in memory
# Arrays are storing actual elements in memory

In [17]:
c = list(range(1,10))
type(c)
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [18]:
c= np.arange(1,10)
print(c)

[1 2 3 4 5 6 7 8 9]


In [19]:
type(c)

numpy.ndarray

In [20]:
# stepping count can be a float in numpy
c = np.arange(1,5,0.5)
print(c)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [21]:
len(c)

8

In [22]:
a = [1,3,"MA"]
b = np.array(a)
print(b)
# converted everything to String , which same datatype

['1' '3' 'MA']


In [23]:
a = [1,2,3,4]
b = np.array(a)
print(b)

[1 2 3 4]


In [24]:
c = np.array(a, dtype="float")
print(c)

[1. 2. 3. 4.]


In [25]:
a = [1,3,"MA"]
b = np.array(a,dtype="float")
print(b)

ValueError: ignored

In [27]:
a = np.array([1,2,3,4,5,6,7,8])
a.ndim

1

In [28]:
a.shape

(8,)

In [29]:
b = a.astype("float")
print(b)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [35]:
b= np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
b= np.arange(1,12)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [37]:
b= np.arange(1,12,2)
print(b)

[ 1  3  5  7  9 11]


In [38]:
# indexing is same as list
b= np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
b[3]

3

In [40]:
b[-1]

11

In [41]:
b[-2]

10

In [42]:
b[-4]

8

In [43]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
b[1:5]

array([1, 2, 3, 4])

In [47]:
b[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
b[:2:-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3])

In [51]:
b[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [53]:
b[:10:-1]

array([11])