<a href="https://colab.research.google.com/github/muralianamala/pythonlearning/blob/main/Scalar_DAV1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Day1 -> Python libraries: Numpy, Pandas, Matplotlib, Seaborn
Day2 -> Probability and Statistics
Day3 -> Hypothesis testing
'''

# **Numpy**

- import numpy as np
- %timeit - to calculate the execution time
- np.array(list) - converts list into np array
- ndim - gives dimensions
- shape - size of array in all dimensions
- np.arange - will create an array with a range of values
- np arrays can store only same datatypes
- Lists are storing references, but arrays are storing actual values in memory
- np.array(a,dtype="dataype") - which creates an array with similar datatype
- .astype(datatype) - converts an array into datatype
- indexing is similar to lists
-

In [ ]:
import numpy as np

In [ ]:
# Numerical in python - numpy means
# Speed comparision
# Numpy is useful wherever numerical operations needed

In [ ]:
l = list(range(10000000))
len(l)

10000000

In [ ]:
%timeit [i**2 for i in l]

3.59 s ± 570 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
b = np.array(l)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#element-wise operation
#ndarray - n dimensional array

In [ ]:
%timeit b**2

27.1 ms ± 464 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
a = np.array((5,7,3,6))
print(a**2)

[25 49  9 36]


In [ ]:
%timeit a**2

563 ns ± 5.97 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
b.ndim

1

In [ ]:
len(b)

10000000

In [ ]:
# it tells me the whole shape of array, if its multi dimensional
b.shape

(10000000,)

In [ ]:
#numpy are arrays, which they can store only same datatypes
#Lists are storing as references in memory
# Arrays are storing actual elements in memory

In [ ]:
c = list(range(1,10))
type(c)
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
c= np.arange(1,10)
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
type(c)

numpy.ndarray

In [ ]:
# stepping count can be a float in numpy
c = np.arange(1,5,0.5)
print(c)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
len(c)

8

In [ ]:
a = [1,3,"MA"]
b = np.array(a)
print(b)
# converted everything to String , which same datatype

['1' '3' 'MA']


In [ ]:
a = [1,2,3,4]
b = np.array(a)
print(b)

[1 2 3 4]


In [ ]:
c = np.array(a, dtype="float")
print(c)

[1. 2. 3. 4.]


In [ ]:
a = [1,3,"MA"]
b = np.array(a,dtype="float")
print(b)

ValueError: ignored

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
a.ndim

1

In [ ]:
a.shape

(8,)

In [ ]:
b = a.astype("float")
print(b)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [ ]:
b= np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b= np.arange(1,12)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b= np.arange(1,12,2)
# start, end, stepcount
print(b)

[ 1  3  5  7  9 11]


In [ ]:
# indexing is same as list
b= np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b[3]
b[::-2]

array([11,  9,  7,  5,  3,  1])

In [ ]:
b[-1]

11

In [ ]:
b[-2]

10

In [ ]:
b[-4]

8

In [ ]:
b

[8, 7, 6]

In [ ]:
b[1:5]

array([1, 2, 3, 4])

In [ ]:
b[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b[:2:-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3])

In [ ]:
b[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
b[:10:-1]

array([11])

In [ ]:
b[-5:11:]

array([ 7,  8,  9, 10])

In [ ]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
arr[2:4] = 0
arr

array([0, 1, 0, 0, 4])

# **MULTIINDEXING**

- array[[,]]

In [ ]:
b = np.arange(1,15,2)
print(b)

[ 1  3  5  7  9 11 13]


In [ ]:
b[2]

5

In [ ]:
b[6]

13

In [ ]:
b[[2,6]]

array([ 5, 13])

In [ ]:
b[[5,2,4]]

array([11,  5,  9])

In [ ]:
a = np.arange(1,30,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [ ]:
a[[5,7,10,11]]

array([11, 15, 21, 23])

# **Fancy Indexing -> Masking**

- Masking is an intersting concept in numpy
- we can filter the records using this
- element wise operator will apply to each an every value within the array
-

In [ ]:
a = np.array([6,9,3,5,7,2,8,1])


In [ ]:
# element-wise operator
a < 6

array([False, False,  True,  True, False,  True, False,  True])

In [ ]:
a [ a<6 ]

array([3, 5, 2, 1])

In [ ]:
# Fliter all the even elements from a, using fancy indexing
a[ a%2==0 ]

array([6, 2, 8])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
b[::-2]


[6, 8]

In [ ]:
a[3:] = b[::-2]
print(a)

[1, 2, 3, 6, 8]


In [ ]:
a[ a%2 != 0]

array([9, 3, 5, 7, 1])

# **NPS Case Study**

In [ ]:
#NPS - Net promoter score
# NPS = %promoters - %Detractors

In [ ]:
'''
%promoters = #of promoters/total users
'''

In [ ]:
score = np.loadtxt("survey.txt", dtype = "int")

In [ ]:
p_rating = score[score > 8]
print(p_rating)

In [ ]:
no_promoters = len(p_rating)
print(no_promoters)

In [ ]:
total = len(score)

In [ ]:
perc_promoters = no_promoters*100/total
print(perc_promoters)

In [ ]:
d_rating = score[score < 7]
no_detractors = len(d_rating)
print(no_detractors)

In [ ]:
perc_detractors = no_detractors*100/total

In [ ]:
nps = perc_promoters - perc_detractors

In [ ]:
nps= np.round(nps,2)

# **NPS CASE Study**

In [ ]:
import numpy as np

In [ ]:
data = np.loadtxt("survey.txt", dtype="int")
total = len(data)

In [ ]:
promoters = data[data>8]
promoters

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [ ]:
#no_promoters = promoters.size
no_promoters = len(promoters)
perc_promoters = (no_promoters * 100)/total
print(perc_promoters)

52.18508997429306


In [ ]:
destructors = data[ data<7]
destructors

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [ ]:
no_dest = len(destructors)
print(no_dest)

332


In [ ]:
perc_dest = (no_dest * 100)/total
perc_dest

28.449014567266495

In [ ]:
nps = perc_promoters - perc_dest
print(np.round(nps,2))

23.74


# **ASSIGNMENT**

In [ ]:
a = np.arange(21,72,2)
print(a)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


In [ ]:
b = np.arange(22,71,2)
print(b)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

b= arr.astype(float)
print(b)

[10. 20. 30. 40. 50.]


In [ ]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

[  5  -9  20  25   3  -5  16 -10  -8]


In [ ]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


In [ ]:
a = np.arange(5,35,3)
print(a)

[ 5  8 11 14 17 20 23 26 29 32]


In [ ]:
np.arange?

In [ ]:
import numpy as np

In [ ]:
x = [[0 1 2] [3 4 5] [6 7 8] [9 10 11]]

[3]


In [ ]:
print(True == 1)

True


# **DAY2**

Following are the topics we shall be covering in the upcoming class.

- Topic 1: Introduction
- Topic 2: Working with 2-D arrays (Matrices)
- Topic 3: Indexing and Slicing in 2D arrays
- Topic 4: Fancy Indexing on 2D arrays
- Topic 5: Aggregate Functions
- Topic 6: Logical Operations
- Topic 7: Logical Operations Contd
- Topic 8: Use Case- Fitbit data analysis
- Topic 9: Basic EDA
- Topic 10: Fitbit Solution
- Topic 11: Doubt Resolution

In [ ]:
import numpy as np

In [ ]:
a = np.array(range(16))

In [ ]:
a.shape

(16,)

In [ ]:
a.ndim

1

## **RESHAPE**

In [ ]:
b = a.reshape(8,2)

In [ ]:
print(b.shape)
print(a.shape)

(8, 2)
(16,)


In [ ]:
b.ndim

2

In [ ]:
#Reshape posisble only certain scenarios
# we can only reshape upto same numbers
c = a.reshape(4,5)
# 4,5 - 4*5 --> 20

ValueError: ignored

In [ ]:
d = a.reshape(8,-1)
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a = a.reshape(8,2)
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
a.ndim

2

In [ ]:
len(a)

8

In [ ]:
len(a[0])

2

## **Transpose of a Matrix**

- a[row,col]

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a[ a>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
b= a.T

In [ ]:
b.shape

(4, 3)

In [ ]:
# nXm --> after transpose --> mXn

In [ ]:
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[0][1]

2

In [ ]:
a[1][2]

6

In [ ]:
a[1,2]

6

In [ ]:
a[2,0]

7

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[2,2]

9

In [ ]:
# Multi indexing in 2d numpy arrays
a = np.array([100,200,300,400,500,600])
a.ndim

1

In [ ]:
a[[2,3]]

array([300, 400])

In [ ]:
a[[2,3,4,1,2,2]]

array([300, 400, 500, 200, 300, 300])

In [ ]:
# multi indexing in 2-D
a = np.arange(9).reshape(3,3)

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a[[2,1],[1,2]]

array([7, 5])

In [ ]:
a[[2,0],[1,1]]

array([7, 1])

In [ ]:
# Task
# use multi indexing in 2D
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a[ [0,1,2],[0,1,2]]

array([0, 4, 8])

In [ ]:
#slicing
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
print(a[:2,:]) # slicing over rows
print(a[:,:2]) # slicing over columns

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [4 5]
 [8 9]]


In [ ]:
a[:,2:3]

array([[ 2],
       [ 6],
       [10]])

In [ ]:
a[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
# Fancy indexing - Masking in 2D

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
a[ a < 6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
import numpy as np
a= np.arange(14).reshape(2,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [ ]:
a[[1,1],[0,2]]

array([7, 9])

## **Aggregate Function**

- SUM
- MIN
- MAX
- COUNT
- AVG

In [ ]:
a= np.arange(1,11)

In [ ]:
np.sum(a)

55

In [ ]:
np.mean(a)

5.5

In [ ]:
np.min(a)

1

In [ ]:
np.max(a)

10

In [ ]:
# Aggregate functions in 2D

In [ ]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 0 --> vertical (columns)
# 1 --> Horizontal (rows)
print(np.argmax(a,axis=0))
print(np.argmax(a,axis=1))
print(np.argmin(a,axis=0))
print(np.argmin(a,axis=1))

print(np.max(a,axis=0))
print(np.max(a,axis=1))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[2 2 2 2]
[3 3 3]
[0 0 0 0]
[0 0 0]
[ 8  9 10 11]
[ 3  7 11]
[0 1 2 3]
[0 4 8]


In [ ]:
# row-wise sum [6,22,38]
np.sum(a,axis=1)

array([ 6, 22, 38])

In [ ]:
#column-wise sum
np.sum(a,axis=0)

array([12, 15, 18, 21])

In [ ]:
np.mean(a,axis=1)

array([1.5, 5.5, 9.5])

In [ ]:
np.mean(a,axis=0)

array([4., 5., 6., 7.])

In [ ]:
np.max(a,axis=1)

array([ 3,  7, 11])

In [ ]:
np.max(a,axis=0)

array([ 8,  9, 10, 11])

In [ ]:
np.min(a,axis=1)

array([0, 4, 8])

In [ ]:
np.min(a,axis=0)

array([0, 1, 2, 3])

## **Logical Operations**

- np.all(logic) - it checks all within an array apply and logic
- np.any(logic) - OR logic

In [ ]:
a = np.array([5,7,2,8,1])
a

array([5, 7, 2, 8, 1])

In [ ]:
a < 3

array([False, False,  True, False,  True])

In [ ]:
a >3

array([ True,  True, False,  True, False])

In [ ]:
#np.all() and np.any()
np.all(a<3)

False

In [ ]:
np.any(a<3)

True

In [ ]:
a = np.array([0,2,3])
b = np.array([1,3,5])
a>=b

array([False, False, False])

In [ ]:
# if lengths are different, cant apply element-wise operation
print(a+b)

[1 5 8]


In [ ]:
arr = np.array([-3,4,27,34,-2,0,-45,-11,4,0])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [ ]:
arr [arr < 0] = -1
arr [arr > 0] = 1
arr

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [ ]:
# WHERE()
# np.where(condition,true(value),false(value)])

In [ ]:
arr = np.where(arr>0,-1,1)
arr

array([ 1, -1, -1, -1,  1,  1,  1,  1, -1,  1])

In [ ]:
arr = np.array([-3,4,27,34,-2,0,-45,-11,4,0])
print(np.where(arr))
# HW -- understand this

(array([0, 1, 2, 3, 4, 6, 7, 8]),)


In [ ]:
import numpy as np

In [ ]:
arr = 2 * np.arange(0,2,0.5)
print(arr)
if np.all(arr):
    print("condition satisfies")
else:
    print("condition doesn't satisfy")

[0. 1. 2. 3.]
condition doesn't satisfy


In [ ]:
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print(v[:,None])
print(x[:,None])
print((x/v[:,None])[1][1])

[[200]
 [300]
 [400]]
[[[200 200 200]]

 [[300 300 300]]

 [[400 400 400]]]
1.0


In [ ]:
p = np.array([[0], [10], [20]])
print(p.shape)
q = np.array([10, 11, 12])
print(q.shape)
print((p + q))
print((p + q)[1][1])

(3, 1)
(3,)
[[10 11 12]
 [20 21 22]
 [30 31 32]]
21


In [ ]:
a = np.array([[16, 5], [81, 6], [33, 1]])
a.shape
a.ndim
print(a.T)
b= a.T.reshape(2,3)
print(b)
print(b.flatten())
print(a.flatten())

[[16 81 33]
 [ 5  6  1]]
[[16 81 33]
 [ 5  6  1]]
[16 81 33  5  6  1]
[16  5 81  6 33  1]


In [ ]:
a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


In [ ]:
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
b = a.T
print(b)
b[-2][-2]

[[34  8 77]
 [28 56 87]
 [55  3 19]]


56

In [ ]:
a = np.array([0,1,2,3,4,5,6,7,8])

b = np.all((a%2 == 0) & (a > 3))
print(b)

False


In [ ]:
a = np.array([[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]])
print(a)
b = a[1:4]
print(b)
c = b[:,len(b[0])-3:len(b[0])+1]
print(c)
print(c[::-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[13 14 15]
 [ 9 10 11]
 [ 5  6  7]]


In [ ]:
a = np.array([[3, 3, 8, 2, 2, 1, 3, 9, 2, 3], [7, 9, 9, 7, 2, 2, 2, 7, 0, 5], [5, 1, 1, 9, 4, 7, 0, 4, 4, 8], [1, 3, 7, 2, 1, 1, 2, 0, 4, 3], [6, 4, 4, 4, 2, 5, 7, 3, 9, 6]])
a.shape
print(a)
b = a[1:4]
print(b)
c = b[:,len(b[0])-3:len(b[0])+1]
print(c)
print(c[::-1])

[[3 3 8 2 2 1 3 9 2 3]
 [7 9 9 7 2 2 2 7 0 5]
 [5 1 1 9 4 7 0 4 4 8]
 [1 3 7 2 1 1 2 0 4 3]
 [6 4 4 4 2 5 7 3 9 6]]
[[7 9 9 7 2 2 2 7 0 5]
 [5 1 1 9 4 7 0 4 4 8]
 [1 3 7 2 1 1 2 0 4 3]]
[[7 0 5]
 [4 4 8]
 [0 4 3]]
[[0 4 3]
 [4 4 8]
 [7 0 5]]


In [ ]:
a = np.array([[6, 28], [8, 56], [7, 19]])
print(a.reshape(1,6))
x = np.transpose(a).reshape(1,6)
print(x)

[[ 6 28  8 56  7 19]]
[[ 6  8  7 28 56 19]]


In [ ]:
a = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
b = a[::-1]
print(b)
print(b.T)

a = np.transpose(a[::-1])
print(a)

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]
[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [ ]:
a = np.array([[0, 1, 2],
 [3, 4, 5],
 [6, 7, 8]])
a
a[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

## **CASE STUDY**

In [ ]:
# HW --> Try to compare the avg steps the user takes when mood is happy and when mood is Sad

In [ ]:
data = np.loadtxt("fit.txt", dtype="str")
data
data.ndim

2

In [ ]:
data.shape
len(data)
print(data)

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

In [ ]:
data_t = data.T
print(data_t)
print(data_t[0])

[['06-10-2017' '07-10-2017' '08-10-2017' '09-10-2017' '10-10-2017'
  '11-10-2017' '12-10-2017' '13-10-2017' '14-10-2017' '15-10-2017'
  '16-10-2017' '17-10-2017' '18-10-2017' '19-10-2017' '20-10-2017'
  '21-10-2017' '22-10-2017' '23-10-2017' '24-10-2017' '25-10-2017'
  '26-10-2017' '27-10-2017' '28-10-2017' '29-10-2017' '30-10-2017'
  '31-10-2017' '01-11-2017' '02-11-2017' '03-11-2017' '04-11-2017'
  '05-11-2017' '06-11-2017' '07-11-2017' '08-11-2017' '09-11-2017'
  '10-11-2017' '11-11-2017' '12-11-2017' '13-11-2017' '14-11-2017'
  '15-11-2017' '16-11-2017' '17-11-2017' '18-11-2017' '19-11-2017'
  '20-11-2017' '21-11-2017' '22-11-2017' '23-11-2017' '24-11-2017'
  '25-11-2017' '26-11-2017' '27-11-2017' '28-11-2017' '29-11-2017'
  '30-11-2017' '01-12-2017' '02-12-2017' '03-12-2017' '04-12-2017'
  '05-12-2017' '06-12-2017' '07-12-2017' '08-12-2017' '09-12-2017'
  '10-12-2017' '11-12-2017' '12-12-2017' '13-12-2017' '14-12-2017'
  '15-12-2017' '16-12-2017' '17-12-2017' '18-12-2017' '19-12-2

In [ ]:
step_count = data_t[1]
print(step_count)

['5464' '6041' '25' '5461' '6915' '4545' '4340' '1230' '61' '1258' '3148'
 '4687' '4732' '3519' '1580' '2822' '181' '3158' '4383' '3881' '4037'
 '202' '292' '330' '2209' '4550' '4435' '4779' '1831' '2255' '539' '5464'
 '6041' '4068' '4683' '4033' '6314' '614' '3149' '4005' '4880' '4136'
 '705' '570' '269' '4275' '5999' '4421' '6930' '5195' '546' '493' '995'
 '1163' '6676' '3608' '774' '1421' '4064' '2725' '5934' '1867' '3721'
 '2374' '2909' '1648' '799' '7102' '3941' '7422' '437' '1231' '1696'
 '4921' '221' '6500' '3575' '4061' '651' '753' '518' '5537' '4108' '5376'
 '3066' '177' '36' '299' '1447' '2599' '702' '133' '153' '500' '2127'
 '2203']


In [ ]:
step_count = np.array(step_count, dtype="int")
print(step_count)

[5464 6041   25 5461 6915 4545 4340 1230   61 1258 3148 4687 4732 3519
 1580 2822  181 3158 4383 3881 4037  202  292  330 2209 4550 4435 4779
 1831 2255  539 5464 6041 4068 4683 4033 6314  614 3149 4005 4880 4136
  705  570  269 4275 5999 4421 6930 5195  546  493  995 1163 6676 3608
  774 1421 4064 2725 5934 1867 3721 2374 2909 1648  799 7102 3941 7422
  437 1231 1696 4921  221 6500 3575 4061  651  753  518 5537 4108 5376
 3066  177   36  299 1447 2599  702  133  153  500 2127 2203]


In [ ]:
mood = data_t[2]
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [ ]:
b = np.unique(mood)
print(b)

['Happy' 'Neutral' 'Sad']


In [ ]:
len(b)

3

In [ ]:
# average step counts for the mood "Happy"
avg_count_happy = np.mean(step_count[mood == "Happy"])
print(avg_count_happy)
happy_step_count = step_count[mood == "Happy"]
print(happy_step_count)

3392.725
[4732  330 4550 4435 4779 1831 2255  539 5464 4068 4683 4033 6314  614
 3149 4005 4880 4136  705  269 4275 5999 4421 6930 5195  546  493  995
 3608  774 1421 4064 2725 5934 1867 7422 5537 5376  153 2203]


In [ ]:
sad_step_count = step_count[mood == "Sad"]
print(sad_step_count)

[6041   25 5461 4545 4340 1230   61 1258 3148 4687 3519 1580 2822  181
 6676 3721 1648  799 1696  221 4061  651  753  518  177   36  299  702
  133]


In [ ]:
#give me step count either happy or nuetral
step_count_either_happy_nuetral = step_count[ (mood == "Happy") | (mood == "Nuetral")]
print(step_count_either_happy_nuetral)

[4732  330 4550 4435 4779 1831 2255  539 5464 4068 4683 4033 6314  614
 3149 4005 4880 4136  705  269 4275 5999 4421 6930 5195  546  493  995
 3608  774 1421 4064 2725 5934 1867 7422 5537 5376  153 2203]


In [ ]:
# Try to compare avg steps the user takes when the mood is Happy and Sad
happy_step_count = step_count[ mood == "Happy"]
sad_step_count = step_count[ mood == "Sad"]
avg_steps_happy = np.mean(happy_step_count)
print(avg_steps_happy)
avg_steps_sad = np.mean(sad_step_count)
print(avg_steps_sad)
print(avg_steps_happy > avg_steps_sad)

3392.725
2103.0689655172414
True


In [ ]:
# explore linspace()



In [ ]:
import numpy as np

In [ ]:
data = np.loadtxt("IPTSFIL_20130211101655_ITEMS.txt", delimiter="|", dtype="str")
data

array([['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', ''],
       ['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', ''],
       ['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', ''],
       ...,
       ['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', ''],
       ['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', ''],
       ['R', 'IPTSFIL', 'AA', ..., '', 'BLOUSES - ANTHRO.', '']],
      dtype='<U25')

In [ ]:
data.ndim

2

In [ ]:
data.size

7872

In [ ]:
len(data[0])

492

In [ ]:
data.T

array([['R', 'R', 'R', ..., 'R', 'R', 'R'],
       ['IPTSFIL', 'IPTSFIL', 'IPTSFIL', ..., 'IPTSFIL', 'IPTSFIL',
        'IPTSFIL'],
       ['AA', 'AA', 'AA', ..., 'AA', 'AA', 'AA'],
       ...,
       ['', '', '', ..., '', '', ''],
       ['BLOUSES - ANTHRO.', 'BLOUSES - ANTHRO.', 'BLOUSES - ANTHRO.',
        ..., 'BLOUSES - ANTHRO.', 'BLOUSES - ANTHRO.',
        'BLOUSES - ANTHRO.'],
       ['', '', '', ..., '', '', '']], dtype='<U25')

In [ ]:
import numpy as np

# **DAY-3**

Following are the topics we shall be covering in the upcoming class.

- Topic 1: Sorting (np.sort(ar,axis=(0,1)), argsort - will display index values of sorted order)
- Topic 2: Element-Wise Multiplication (will multiple on element-wise)
- Topic 3: Matrix multiplication. (np.dot(a,b),a@b,np.matmul(a.b)
- Topic 4: Vectorization (will call funtion by sending array)
- Topic 5: Broadcasting
- Topic 6: Quiz-4 Explanation
- Topic 7: Quiz-5 Explanation
- Topic 8: Doubt Resolution

In [ ]:
a = np.array([[23,4,43],
             [12,89,3],
             [69,420,0]])
b = np.sort(a)
b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [ ]:
b = np.sort(a, axis=1)
b

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

In [ ]:
b = np.sort(a,axis=0)
b

array([[ 12,   4,   0],
       [ 23,  89,   3],
       [ 69, 420,  43]])

In [ ]:
#element-wise operations
a = np.arange(5)
b = np.arange(5)
#b = np.ones(5)
print(a)
print(b)

[0 1 2 3 4]
[0 1 2 3 4]


In [ ]:
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
a*b

array([ 0,  1,  4,  9, 16])

In [ ]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
b = np.arange(2,14).reshape(3,4)
print(b)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [ ]:
b.shape

(3, 4)

In [ ]:
print(a+b)

[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]]


In [ ]:
a*b

array([[  2,   6,  12,  20],
       [ 30,  42,  56,  72],
       [ 90, 110, 132, 156]])

In [ ]:
#c1=r2
#r1Xc2

In [ ]:
'''
Matrix multiplication
1. np.dot
2. @ operater
3. mp.amtmul
'''

In [ ]:
a = np.arange(1,13).reshape(3,4)
b= np.arange(2,14).reshape(4,3)

In [ ]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [ ]:
#way1
c= np.dot(a,b)
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [ ]:
#way2
c= a@b
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [ ]:
#way3
c = np.matmul(a,b)
print(c)

[[ 80  90 100]
 [184 210 236]
 [288 330 372]]


In [ ]:
a = np.arange(5)
b= np.arange(1,6)
print(a)
print(b)
print(a.shape)
print(b.shape)

[0 1 2 3 4]
[1 2 3 4 5]
(5,)
(5,)


In [ ]:
c = np.dot(a,b)
print(c)
#HW --> understand what exactly happend

40


In [ ]:
#vectorization
#Vectorization in NumPy refers to performing operations on entire arrays or array elements simultaneously, which is significantly faster and more efficient than using explicit loops.


# **vectorization**

- Vectorization in NumPy refers to performing operations on entire arrays or array elements simultaneously, which is significantly faster and more efficient than using explicit loops.


In [ ]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [ ]:
def solve(n):
  if n%2 ==0:
    n+=2
  else:
    n-=2
  return n


solve(10)

12

In [ ]:
solve(3)

1

In [ ]:
solve(7)

5

In [ ]:
#function called on each and every field within an array
#by calling function
new_solve = np.vectorize(solve)
print(new_solve(a))

[ 2 -1  4  1  6  3  8  5 10]


# **Broadcasting**

- ntile(array,(m,n))


In [ ]:
a = np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [ ]:
#np.tile
c = np.tile(a,(3,1))
c

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
b = np.tile(a,(3,2))
b

array([[ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30],
       [ 0, 10, 20, 30,  0, 10, 20, 30]])

In [ ]:
b.shape

(3, 8)

In [ ]:
a = np.arange(0,40,10)
a = np.tile(a,(3,1))
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [ ]:
a.T

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [ ]:
b = np.arange(3)
b

array([0, 1, 2])

In [ ]:
b = np.tile(b,(4,1))
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
a+b

ValueError: ignored

In [ ]:
#case3


In [ ]:
a= np.arange(0,40,10)
a

array([ 0, 10, 20, 30])

In [ ]:
a = a.reshape(4,1)
a

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
a.shape

(4, 1)

In [ ]:
b = np.arange(0,3)
b

array([0, 1, 2])

In [ ]:
b.shape

(3,)

In [ ]:
print(a+b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
'''
Explanation
(4,1)
(1,3)
rule1 --> match the number either in row or columns
rule2 --> any one have 1

(4,3)

#case 2
a --> (4,3)
b --> (1,3)

c --> (4,3)
'''

In [ ]:
a = np.arange(8).reshape(2,4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
b = np.arange(16).reshape(4,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
import numpy as np
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
arr = np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]]) #(4,4)
arr

array([[ 2,  3,  4,  5],
       [ 1,  7,  3,  5],
       [ 2,  8,  6,  9],
       [11, 23, 12, 19]])

In [ ]:
arr1 = np.array([[2,2,2,2]]) #(1,4)
def func(x,y):
  return x*y
vec = np.vectorize(func)
print(vec(arr,arr1))

[[ 4  6  8 10]
 [ 2 14  6 10]
 [ 4 16 12 18]
 [22 46 24 38]]


In [ ]:
arr1 = np.array([[2],[2],[2],[2]]) #(4,1)
def func(x, y):
    return x * y
vec = np.vectorize(func)
print(vec(arr, arr1))

[[ 4  6  8 10]
 [ 2 14  6 10]
 [ 4 16 12 18]
 [22 46 24 38]]


In [ ]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
print(vec(arr, arr1))

[[ 4  6  8 10]
 [ 2 14  6 10]
 [ 4 16 12 18]
 [22 46 24 38]]


In [ ]:
def specific_elements(mat1,mat2,r1,r2,c1,c2):
  if (len(mat1[0]) != len(mat2)):
    result = -1
    return result
  matmul_array = np.matmul(mat1,mat2)
  print(matmul_array)
  result = matmul_array[r1:r2,c1:c2]
  return result

#mat1 = np.array([[6,6,4,7,9],[0,2,2,9,3],[6,0,2,5,2],[2,4,3,5,5]])
mat1 = np.array([[6,4,7,9],[2,2,9,3],[0,2,5,2],[4,3,5,5]])
mat2 = np.array([[8,6,6,8,3],[2,7,0,3,1],[3,2,1,5,2],[7,0,7,6,8],[1,5,6,4,5]])

print(specific_elements(mat1,mat2,1,3,2,4))

-1


In [ ]:
def sort_birds(birds,age):
  '''
  INPUT: birds, age -> 1D numpy array

  OUTPUT: result -> sorted bird 1D array
  '''

  ## STEP 1 : Get the sorted index of age.

  sorted_age_index = np.argsort(age)
  print(sorted_age_index)
  ## STEP 2: Use the index from previous step to get sorted birds

  result = birds[sorted_age_index]

  return result

In [ ]:
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])
print(sort_birds(birds,age))

[3 7 4 2 6 5 0 8 1 9]
['plovers' 'plovers' 'plovers' 'plovers' 'plovers' 'Cranes' 'spoonbills'
 'Cranes' 'plovers' 'spoonbills']


In [ ]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [ ]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [ ]:
import numpy as np

def calculate_mean_age(birds, age):
    '''
    INPUT: birds, age -> 1D array

    OUPUT: mean_age -> float variable
    '''

    mean_age = None

    ## STEP1. Create mask to get Crane birds from birds array
    mask = (birds == 'Cranes')

    ## STEP2. Get the age of crane birds

    crane_ages = age[mask]
    print(crane_ages)

    ## STEP 3. Calculate mean age of crane birds

    mean_age = ''

    ## STEP 4. Round off the mean age to 2 decimal points

    mean_age = ''



    return mean_age

In [ ]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

birds= np.array(birds)
age = np.array(age)

age = age[birds == 'Cranes']
mean_age = np.round(np.mean(age),2)
print(age)
print(mean_age)
#calculate_mean_age(birds,age)

[4.  5.5]
4.75


In [ ]:
birds = np.array(['sparrow', 'peacock', 'parrot', 'owl', 'peacock', 'macaw', 'macaw', 'parrot', 'macaw', 'peacock'])
age = np.array([6, 1, 6, 5, 7, 6, 0, 9, 0, 7])
max_age = np.argmax(age)
print(max_age)
print(birds[max_age])

7
parrot


In [ ]:
arr1 = np.array([1,2,3,6,3,2])
arr2 = np.array([4,2,1,3,3,2])
arr3 = np.zeros(len(arr1))

In [ ]:
for i in range(len(arr1)):
    arr3[i] = arr1[i] * arr2[i]
print(arr3)

[ 4.  4.  3. 18.  9.  4.]


In [ ]:
arr3= arr2 * arr1
print(arr3)

[ 4  4  3 18  9  4]


In [ ]:
for i in range(len(arr1)):
    if(arr1[i] < 0 ):
        arr1[i] = -1
    else:
        arr1[i] = 1

print(arr1)

[1 1 1 1 1 1]


In [ ]:
arr1 = np.array([1,2,3]) # 1,3
arr2 = np.array([9,8,7]) # 1,3
np.dot(arr1, arr2)

46

In [ ]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [ ]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [ ]:
arr1 = np.array([[1,2], [3,4]])
print(arr1.shape)
arr2 = np.array([1,1])
print(arr2.shape)
c = arr1@arr2
print(c)

(2, 2)
(2,)
[3 7]


In [ ]:
A = np.arange(9).reshape(3,3)
print(A)
print(A[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [ ]:
arr = [a+" "+b for a in [ 'Hello', 'Good'] for b in ['Dear', 'Bye']]
print(arr)

['Hello Dear', 'Hello Bye', 'Good Dear', 'Good Bye']


In [ ]:
a = [1,2,3,4,5,6,7,8,9]
b = [i for i in a if i>6]
print(b)

[7, 8, 9]


In [ ]:
a=[1,2,3,4]
b =[4,5,6,7]
c = [i*j for i in a for j in b]
print(c)

[4, 5, 6, 7, 8, 10, 12, 14, 12, 15, 18, 21, 16, 20, 24, 28]


In [ ]:
arr = [[1,2,3],[10,11,12],[4,5,6],[13,14,15],[10,1,2]]

print(max (arr, key=sum ) )
print(max(arr))

[13, 14, 15]
[13, 14, 15]


In [ ]:
list1 = ['Apple', 'Berry', 'Cherry', 'Papaya']
list2 = list1
list3 = list1[:]

list2[0] = 'Guava'
list3[1] = 'Kiwi'
print(list1)
print(list2)
print(list3)
total = 0
s = (list1,list2,list3)
print(s)
for ls in (list1, list2, list3):
  if ls[0] == 'Guava':
    total += 1

  if ls[1] == 'Kiwi':
    total += 20

print (total, list3[0])

['Guava', 'Berry', 'Cherry', 'Papaya']
['Guava', 'Berry', 'Cherry', 'Papaya']
['Apple', 'Kiwi', 'Cherry', 'Papaya']
(['Guava', 'Berry', 'Cherry', 'Papaya'], ['Guava', 'Berry', 'Cherry', 'Papaya'], ['Apple', 'Kiwi', 'Cherry', 'Papaya'])
22 Apple


In [ ]:
Menu = [['Sweet_Corn_Soup', 300.0], ['Cream_of_Tomato_Soup', 100.0], ['Bacon_and_Cheese', 150.0], ['Honey_Mustard', 230.0], ['Hot_Coffee', 50.0], ['Cold_Coffee', 50.0], ['Egg_Sandwiches', 130.0], ['Tacos', 400.0]]
print(Menu)

[['Sweet_Corn_Soup', 300.0], ['Cream_of_Tomato_Soup', 100.0], ['Bacon_and_Cheese', 150.0], ['Honey_Mustard', 230.0], ['Hot_Coffee', 50.0], ['Cold_Coffee', 50.0], ['Egg_Sandwiches', 130.0], ['Tacos', 400.0]]


In [ ]:
item_list =["Hot_Coffee","Cold_Coffee","Tacos"]

for i in range(len(Menu)):
  print(Menu[i][0])
  for j in item_list:
    if j == Menu[i][0]:
      print(Menu[i][0], Menu[i][1])
      Menu[i][1] = round(1.1 * Menu[i][1])
      print(Menu[i][1])
    else:
      continue
  i += 1
print(Menu)

Sweet_Corn_Soup
Cream_of_Tomato_Soup
Bacon_and_Cheese
Honey_Mustard
Hot_Coffee
Hot_Coffee 50.0
55
Cold_Coffee
Cold_Coffee 50.0
55
Egg_Sandwiches
Tacos
Tacos 400.0
440
[['Sweet_Corn_Soup', 300.0], ['Cream_of_Tomato_Soup', 100.0], ['Bacon_and_Cheese', 150.0], ['Honey_Mustard', 230.0], ['Hot_Coffee', 55], ['Cold_Coffee', 55], ['Egg_Sandwiches', 130.0], ['Tacos', 440]]


# **DAY4**

Following are the topics we shall be covering in the upcoming class.

- Topic 1: Views vs Copies (Shallow vs Deep Copy)
- Topic 2: Checking memory sharing using `np.shares_memory()`
- Topic 3: Understanding `.view()`
- Topic 4: Making Deep Cody using `.copy()`
- Topic 5: Array Splitting
- Topic 6: Understanding horizontal and vertical split
- Topic 7: Stacking (`vtack`)
- Topic 8: Stacking (`htack`)
- Topic 9: Understanding `np.concatenate()`
- Topic 10: Quiz-4 Explanation
- Topic 11: Doubt Resolution

In [ ]:
# Shallow copy
# Deep copy

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = a.reshape(2,2)
print(b)

[[0 1]
 [2 3]]


In [ ]:
a[0] = 11

In [ ]:
print(a)
print(b)

[11  1  2  3]
[[11  1]
 [ 2  3]]


In [ ]:
np.shares_memory(a,b) # Shallow copy

True

In [ ]:
c = a #shallow copy

In [ ]:
print(c)

[11  1  2  3]


In [ ]:
a[1]=15

In [ ]:
print(c)

[11 15  2  3]


In [ ]:
np.shares_memory(a,c)

True

In [ ]:
#eg 3
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = a[::2] # slicing --> shallow copy
b

array([1, 3, 5, 7, 9])

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
a[0] = 90
a

array([90,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b

array([90,  3,  5,  7,  9])

In [ ]:
a[1] = 70
print(a)
print(b)

[90 70  3  4  5  6  7  8  9 10]
[90  3  5  7  9]


Slicing creates a shallow copy

In [ ]:
a = np.arange(1,6)
print(a)

[1 2 3 4 5]


In [ ]:
b = a[a%2 == 0]
b

array([2, 4])

In [ ]:
np.shares_memory(a,b) # deep copy

False

a and b are not sharing same memory, this concept called deep copy

In [ ]:
a[1] = 100
a

array([  1, 100,   3,   4,   5])

In [ ]:
b

array([2, 4])

In [ ]:
# Shallow copy  --> Reshaping, slicing, assigning
# Deep copy --> masking, arithmatic operation

In [ ]:
#.view() --> Shallow copy

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a.view()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[3] = 100
b

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [ ]:
np.shares_memory(a,b)

True

In [ ]:
#deep copy
#.copy()

In [ ]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [ ]:
#b = np.copy(a)
b = a.copy()
b

array([1, 2, 3, 4, 5])

In [ ]:
a[1]=100
b

array([1, 2, 3, 4, 5])

In [ ]:
np.shares_memory(a,b)

False

In [ ]:
#version2
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.split(a,2)
print(b)
d = np.split(a,5)
print(d)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [ ]:
c = np.split(a, [3,5,6])
c

[array([1, 2, 3]), array([4, 5]), array([6]), array([ 7,  8,  9, 10])]

In [ ]:
e = np.split(a,[3,6,9])
e

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10])]

In [ ]:
a = np.arange(2,15)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
b = np.split(a,[3,6,10])
b

[array([2, 3, 4]),
 array([5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14])]

In [ ]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b = np.split(a,[2,4,7,8])
b

[array([1, 2]), array([3, 4]), array([5, 6, 7]), array([8]), array([ 9, 10])]

## **SPLIT in 2D**

- hsplit -- horizontal
- vsplit -- vertical

In [ ]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#hsplit -- split the horizontal axis -- column-wise split
b = np.hsplit(a,2)
b

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
b = np.hsplit(a,[1,2])
b

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
c = np.vsplit(a,2)
c

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
c = np.vsplit(a,[1,2])
c

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
c = np.vsplit(a,[2,3])
c

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

## **CONCATENATION**

In [ ]:
a = np.array([[2,4]])
a.ndim
a.shape

(1, 2)

In [ ]:
b = np.concatenate([a,a], axis=0)
print(b)

[[2 4]
 [2 4]]


In [ ]:
c = np.concatenate([a,a], axis=1)
print(c)
c.shape

[[2 4 2 4]]


(1, 4)

In [ ]:
#stacking
#hstack
#vstack


In [ ]:
a = np.array([[2,4,3]])
a

array([[2, 4, 3]])

In [ ]:
b = np.array([[5,4]])
b

array([[5, 4]])

In [ ]:
c = np.concatenate([a,b], axis=1)
c

array([[2, 4, 3, 5, 4]])

In [ ]:
a = np.arange(5)
b = np.arange(5,10)
print(a)
print(b)

[0 1 2 3 4]
[5 6 7 8 9]


In [ ]:
c = np.hstack((a,b))
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
d = np.vstack((b,a))
d

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [ ]:
a = np.array([[1],[2],[3]])
print(a.shape)
b = np.array([[4],[5],[6]])
print(b.shape)
c = np.vstack((a,b))
print(c)
print(c.shape)
d = np.hstack((a,b))
d

(3, 1)
(3, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


array([[1, 4],
       [2, 5],
       [3, 6]])

# **PANDAS**

- Topic 1: Introduction
- Topic 2: Installation of Pandas
- Topic 3: DataFrame and Series
- Topic 4: Pandas Series
- Topic 5: Basic operations on columns
- Topic 6: Basic Operations on Columns Contd
- Topic 7: Working with Rows
- Topic 8: loc
- Topic 9: iloc
- Topic 10: columns as row index

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# data frame (df)
# df.head(n) -- no of top rows will return, by default will return 5 rows
# df.tail(n) -- no of bottom rows will return, by default will return 5 rows
# df.shape -- shape of array
# df["column_name"] -- returns all values in that column
# type(df) -- pandas.core.frame.DataFrame
# type(df["column_name"]) -- pandas.core.frame.Series
# df.info() - info about data frame
# String referred as object datatype in Pandas
# row-oriented apporach to create data frame
#

In [ ]:
sample_df= pd.DataFrame([
    ['India',1952,842,'Asia',28.03,77.42]
],

columns=['country','year','population','continent','life_exp','gdp_cap']
)

In [ ]:
sample_df

country  year  population continent  life_exp  gdp_cap
0   India  1952         842      Asia     28.03    77.42

In [ ]:
# column - oriented approach
sample_df.head()

country  year  population continent  life_exp  gdp_cap
0   India  1952         842      Asia     28.03    77.42

In [ ]:
df = pd.read_csv("mckinsey.csv")

In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.tail()

country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [ ]:
df.head(10)

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106
5  Afghanistan  1977    14880372      Asia    38.438  786.113360
6  Afghanistan  1982    12881816      Asia    39.854  978.011439
7  Afghanistan  1987    13867957      Asia    40.822  852.395945
8  Afghanistan  1992    16317921      Asia    41.674  649.341395
9  Afghanistan  1997    22227415      Asia    41.763  635.341351

In [ ]:
df.tail(10)

country  year  population continent  life_exp     gdp_cap
1694  Zimbabwe  1962     4277736    Africa    52.358  527.272182
1695  Zimbabwe  1967     4995432    Africa    53.995  569.795071
1696  Zimbabwe  1972     5861135    Africa    55.635  799.362176
1697  Zimbabwe  1977     6642107    Africa    57.674  685.587682
1698  Zimbabwe  1982     7636524    Africa    60.363  788.855041
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [ ]:
df['continent']

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...  
1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, Length: 1704, dtype: object

In [ ]:
df[ ['continent','country']].head()

continent      country
0      Asia  Afghanistan
1      Asia  Afghanistan
2      Asia  Afghanistan
3      Asia  Afghanistan
4      Asia  Afghanistan

In [ ]:
df.shape

(1704, 6)

In [ ]:
type(df['continent'])

pandas.core.series.Series

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     1704 non-null   object 
 1   year        1704 non-null   int64  
 2   population  1704 non-null   int64  
 3   continent   1704 non-null   object 
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [ ]:
# row - oriented approach
sample_df = pd.DataFrame(
    [
        ['India',1952,8425333,'Asia',28.801,779.445314],
        ['Afganisthan',1957,9240934,'Asia',30.332,820.853]

    ],
    columns = ['country','year','population','continent','life_exp','gdp_cap']
)

In [ ]:
sample_df

country  year  population continent  life_exp     gdp_cap
0        India  1952     8425333      Asia    28.801  779.445314
1  Afganisthan  1957     9240934      Asia    30.332  820.853000

In [ ]:
# column-oriented approach
df2 = pd.DataFrame(
    {
        'country':['India','Afganisthan','China'],
        'year' : [1952,1957,1932],
        'population' : [8425333,9240934,812653],
        'continent' : ['Asia','Asia','Asia'],
        'life_exp' : [28.801,30.322,18.12],
        'gdp_cap' : [779.445314,820.853030,123.12]
    }
)

df2

country  year  population continent  life_exp     gdp_cap
0        India  1952     8425333      Asia    28.801  779.445314
1  Afganisthan  1957     9240934      Asia    30.322  820.853030
2        China  1932      812653      Asia    18.120  123.120000

In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
print(df.columns)

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')


In [ ]:
df.columns[3]

'continent'

In [ ]:
df[ ['country'] ].head()

country
0  Afghanistan
1  Afghanistan
2  Afghanistan
3  Afghanistan
4  Afghanistan

In [ ]:
df.continent.head()

0    Asia
1    Asia
2    Asia
3    Asia
4    Asia
Name: continent, dtype: object

In [ ]:
df2 = df[ ['country','continent']].head()
df2

country continent
0  Afghanistan      Asia
1  Afghanistan      Asia
2  Afghanistan      Asia
3  Afghanistan      Asia
4  Afghanistan      Asia

In [ ]:
# basic operations on columns
unique_countries = df['country'].unique()
unique_countries

array(['Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
       'Australia', 'Austria', 'Bahrain', 'Bangladesh', 'Belgium',
       'Benin', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon',
       'Canada', 'Central African Republic', 'Chad', 'Chile', 'China',
       'Colombia', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Czech Republic',
       'Denmark', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Ethiopia',
       'Finland', 'France', 'Gabon', 'Gambia', 'Germany', 'Ghana',
       'Greece', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Haiti',
       'Honduras', 'Hong Kong, China', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kenya', 'Korea, Dem. Rep.',
       'Korea, Rep.', 'Kuwait', 'Leba

In [ ]:
df['country'].nunique()

142

In [ ]:
len(df['country'].unique())

142

In [ ]:
unique_continents = df['continent'].unique()
print(unique_continents)
count_of_unique_continents = df['continent'].nunique()
print(count_of_unique_continents)


['Asia' 'Europe' 'Africa' 'Americas' 'Oceania']
5


In [ ]:
# value - counts
print(df['continent'].value_counts())
len(df['continent'])

Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: continent, dtype: int64


1704

In [ ]:
# renaming of a column
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.rename({"country" : "Country","population" : "Population"}, axis=1) # default axis is zero


Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.rename({"country" : "Country","population" : "Population"}, axis=1, inplace=True)

In [ ]:
df.head()

Country  year  Population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
# delete a column
df.drop('continent', axis=1)

Country  year  Population  life_exp     gdp_cap
0     Afghanistan  1952     8425333    28.801  779.445314
1     Afghanistan  1957     9240934    30.332  820.853030
2     Afghanistan  1962    10267083    31.997  853.100710
3     Afghanistan  1967    11537966    34.020  836.197138
4     Afghanistan  1972    13079460    36.088  739.981106
...           ...   ...         ...       ...         ...
1699     Zimbabwe  1987     9216418    62.351  706.157306
1700     Zimbabwe  1992    10704340    60.377  693.420786
1701     Zimbabwe  1997    11404948    46.809  792.449960
1702     Zimbabwe  2002    11926563    39.989  672.038623
1703     Zimbabwe  2007    12311143    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
df

Country  year  Population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.drop('continent', axis=1, inplace=True)

In [ ]:
df.head()

Country  year  Population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [ ]:
# way2
df.head()

Country  year  Population  life_exp     gdp_cap
0  Afghanistan  1952     8425333    28.801  779.445314
1  Afghanistan  1957     9240934    30.332  820.853030
2  Afghanistan  1962    10267083    31.997  853.100710
3  Afghanistan  1967    11537966    34.020  836.197138
4  Afghanistan  1972    13079460    36.088  739.981106

In [ ]:
df_renamed = df.rename({'country':'Country','population':'Population'}, axis=1)

In [ ]:
df_renamed.head()

Country  year  Population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df_renamed.drop(columns=['Population'], inplace=True)
df_renamed

Country  year continent  life_exp     gdp_cap
0     Afghanistan  1952      Asia    28.801  779.445314
1     Afghanistan  1957      Asia    30.332  820.853030
2     Afghanistan  1962      Asia    31.997  853.100710
3     Afghanistan  1967      Asia    34.020  836.197138
4     Afghanistan  1972      Asia    36.088  739.981106
...           ...   ...       ...       ...         ...
1699     Zimbabwe  1987    Africa    62.351  706.157306
1700     Zimbabwe  1992    Africa    60.377  693.420786
1701     Zimbabwe  1997    Africa    46.809  792.449960
1702     Zimbabwe  2002    Africa    39.989  672.038623
1703     Zimbabwe  2007    Africa    43.487  469.709298

[1704 rows x 5 columns]

In [ ]:
# Creating a new column
df["year+7"] = df["year"] + 7
df.head()

country  year  population continent  life_exp     gdp_cap  year+7
0  Afghanistan  1952     8425333      Asia    28.801  779.445314    1959
1  Afghanistan  1957     9240934      Asia    30.332  820.853030    1964
2  Afghanistan  1962    10267083      Asia    31.997  853.100710    1969
3  Afghanistan  1967    11537966      Asia    34.020  836.197138    1974
4  Afghanistan  1972    13079460      Asia    36.088  739.981106    1979

In [ ]:
# GDP_cap = GDP/population

In [ ]:
df['gdp'] = df['population'] * df['gdp_cap']
df.head()

country  year  population continent  life_exp     gdp_cap  year+7  \
0  Afghanistan  1952     8425333      Asia    28.801  779.445314    1959   
1  Afghanistan  1957     9240934      Asia    30.332  820.853030    1964   
2  Afghanistan  1962    10267083      Asia    31.997  853.100710    1969   
3  Afghanistan  1967    11537966      Asia    34.020  836.197138    1974   
4  Afghanistan  1972    13079460      Asia    36.088  739.981106    1979   

            gdp  
0  6.567086e+09  
1  7.585449e+09  
2  8.758856e+09  
3  9.648014e+09  
4  9.678553e+09

In [ ]:
a = []
for i in range(1,1705):
  a.append(i)

In [ ]:
df['new_col'] = a
df.head()
df.tail()

country  year  population continent  life_exp     gdp_cap  year+7  \
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306    1994   
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786    1999   
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960    2004   
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623    2009   
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298    2014   

               gdp  new_col  
1699  6.508241e+09     1700  
1700  7.422612e+09     1701  
1701  9.037851e+09     1702  
1702  8.015111e+09     1703  
1703  5.782658e+09     1704

In [ ]:
df.drop(columns=['new_col','gdp','year+7'], inplace=True)


In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
# Data Frame indexing
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.index.values

array([   0,    1,    2, ..., 1701, 1702, 1703])

In [ ]:
ind = []
n = len(df.index.values)
for i in range(1,n+1):
  ind.append(i)

In [ ]:
print(ind)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [ ]:
df.index = ind

In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710
4  Afghanistan  1967    11537966      Asia    34.020  836.197138
5  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
'''
Types of Row indexing
Implicit indexing --> 0 - iloc
Explicit index --> visible - loc
'''

Index(['country', 'year', 'population', 'continent', 'life_exp', 'gdp_cap'], dtype='object')

In [ ]:
df.loc[1]

country       Afghanistan
year                 1952
population        8425333
continent            Asia
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [ ]:
df.iloc[0]

country       Afghanistan
year                 1952
population        8425333
continent            Asia
life_exp           28.801
gdp_cap        779.445314
Name: 1, dtype: object

In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710
4  Afghanistan  1967    11537966      Asia    34.020  836.197138
5  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.loc[1:3]

country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710

In [ ]:
df.iloc[:3]

country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710

In [ ]:
df.loc[::-1].head()

country  year  population continent  life_exp     gdp_cap
1704  Zimbabwe  2007    12311143    Africa    43.487  469.709298
1703  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1702  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1701  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1700  Zimbabwe  1987     9216418    Africa    62.351  706.157306

In [ ]:
# Accessing multiple rows

df.loc[ [1,100] ]

country  year  population continent  life_exp     gdp_cap
1    Afghanistan  1952     8425333      Asia    28.801  779.445314
100   Bangladesh  1967    62821884      Asia    43.453  721.186086

In [ ]:
df.iloc[ [1, 100]]

country  year  population continent  life_exp     gdp_cap
2    Afghanistan  1957     9240934      Asia    30.332  820.853030
101   Bangladesh  1972    70759295      Asia    45.252  630.233627

In [ ]:
# SET and RESET index
temp = df.set_index('country')
temp.head()

year  population continent  life_exp     gdp_cap
country                                                      
Afghanistan  1952     8425333      Asia    28.801  779.445314
Afghanistan  1957     9240934      Asia    30.332  820.853030
Afghanistan  1962    10267083      Asia    31.997  853.100710
Afghanistan  1967    11537966      Asia    34.020  836.197138
Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
temp.loc['Afghanistan']

year  population continent  life_exp     gdp_cap
country                                                      
Afghanistan  1952     8425333      Asia    28.801  779.445314
Afghanistan  1957     9240934      Asia    30.332  820.853030
Afghanistan  1962    10267083      Asia    31.997  853.100710
Afghanistan  1967    11537966      Asia    34.020  836.197138
Afghanistan  1972    13079460      Asia    36.088  739.981106
Afghanistan  1977    14880372      Asia    38.438  786.113360
Afghanistan  1982    12881816      Asia    39.854  978.011439
Afghanistan  1987    13867957      Asia    40.822  852.395945
Afghanistan  1992    16317921      Asia    41.674  649.341395
Afghanistan  1997    22227415      Asia    41.763  635.341351
Afghanistan  2002    25268405      Asia    42.129  726.734055
Afghanistan  2007    31889923      Asia    43.828  974.580338

In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
1  Afghanistan  1952     8425333      Asia    28.801  779.445314
2  Afghanistan  1957     9240934      Asia    30.332  820.853030
3  Afghanistan  1962    10267083      Asia    31.997  853.100710
4  Afghanistan  1967    11537966      Asia    34.020  836.197138
5  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.reset_index(drop = True, inplace=True)

In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.loc[ 1, ["year","population"]]

year             1957
population    9240934
Name: 1, dtype: object

In [ ]:
print(df.iloc[1])
print(df.loc[1])

country       Afghanistan
year                 1957
population        9240934
continent            Asia
life_exp           30.332
gdp_cap         820.85303
Name: 1, dtype: object
country       Afghanistan
year                 1957
population        9240934
continent            Asia
life_exp           30.332
gdp_cap         820.85303
Name: 1, dtype: object


In [ ]:
df.loc[1:5,["year"]]

year
1  1957
2  1962
3  1967
4  1972
5  1977

In [ ]:
df1 = pd.read_csv("tips.csv")


In [ ]:
df1.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df1[ ['time'] ]

time
0    Dinner
1    Dinner
2    Dinner
3    Dinner
4    Dinner
..      ...
239  Dinner
240  Dinner
241  Dinner
242  Dinner
243  Dinner

[244 rows x 1 columns]

In [ ]:
df1.loc[:,['time']]

time
0    Dinner
1    Dinner
2    Dinner
3    Dinner
4    Dinner
..      ...
239  Dinner
240  Dinner
241  Dinner
242  Dinner
243  Dinner

[244 rows x 1 columns]

In [ ]:
pd.DataFrame(df1, columns=['time','tip'])

time   tip
0    Dinner  1.01
1    Dinner  1.66
2    Dinner  3.50
3    Dinner  3.31
4    Dinner  3.61
..      ...   ...
239  Dinner  5.92
240  Dinner  2.00
241  Dinner  2.00
242  Dinner  1.75
243  Dinner  3.00

[244 rows x 2 columns]

In [ ]:
df1.iloc[:,:2]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [ ]:
df1.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df1.iloc[:2,:2]

total_bill   tip
0       16.99  1.01
1       10.34  1.66

In [ ]:
df2 = pd.read_csv("mtcars.csv")


In [ ]:
df2.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [ ]:
df3 = df2.set_index('model')

In [ ]:
df3.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
model                                                                        
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
model                    
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

In [ ]:
df3.iloc[1:5,3:5]

hp  drat
model                       
Mazda RX4 Wag      110  3.90
Datsun 710          93  3.85
Hornet 4 Drive     110  3.08
Hornet Sportabout  175  3.15

In [ ]:
df3.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
model                                                                        
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
model                    
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

In [ ]:
#df3.loc[:,'disp']
#df3['disp']


In [ ]:
d = pd.DataFrame({'name':["Sam","Roma","Mark"], "profession":['dev','mle','Data scientist'],"gender":['male','female','male'], "age":[21,20,25],"review":['No comments','hardworker','need improvement'],"rating":[10,5,7]})

In [ ]:
d.head()

name      profession  gender  age            review  rating
0   Sam             dev    male   21       No comments      10
1  Roma             mle  female   20        hardworker       5
2  Mark  Data scientist    male   25  need improvement       7

In [ ]:
new = d.loc[d.rating >= 6, ['profession','gender','age']]

In [ ]:
new.head()

profession gender  age
0             dev   male   21
2  Data scientist   male   25

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("mckinsey.csv")
df

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.tail()

country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   country     1704 non-null   object 
 1   year        1704 non-null   int64  
 2   population  1704 non-null   int64  
 3   continent   1704 non-null   object 
 4   life_exp    1704 non-null   float64
 5   gdp_cap     1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [ ]:
df.iloc[1:5, 1:4]

year  population continent
1  1957     9240934      Asia
2  1962    10267083      Asia
3  1967    11537966      Asia
4  1972    13079460      Asia

In [ ]:
df.loc[1:5, ["continent","gdp_cap"]]

continent     gdp_cap
1      Asia  820.853030
2      Asia  853.100710
3      Asia  836.197138
4      Asia  739.981106
5      Asia  786.113360

In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.loc[2:6, "population":"life_exp"]

population continent  life_exp
2    10267083      Asia    31.997
3    11537966      Asia    34.020
4    13079460      Asia    36.088
5    14880372      Asia    38.438
6    12881816      Asia    39.854

In [ ]:
df.iloc[ [0,10,20],[0,2,3]]

country  population continent
0   Afghanistan     8425333      Asia
10  Afghanistan    25268405      Asia
20      Albania     3326498    Europe

In [ ]:
df.iloc[1:12:2, 1:2]

year
1   1957
3   1967
5   1977
7   1987
9   1997
11  2007

In [ ]:
df.tail()

country  year  population continent  life_exp     gdp_cap
1699  Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298

In [ ]:
new_row = {'country':'India', 'year':2000, 'population':13500000, 'continent':'Asia', 'life_exp':37.08,  'gdp_cap':900.23}

In [ ]:
df.append(new_row, ignore_index=True)

<ipython-input-18-85c282e4af20>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(new_row, ignore_index=True)


country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2000    13500000      Asia    37.080  900.230000

[1705 rows x 6 columns]

In [ ]:
df.loc[len(df.index)] = ['India', 2000, 13500000, "Asia", 37.08, 900.23] #appending a row at the end
df.tail()

country  year  population continent  life_exp     gdp_cap
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704     India  2000    13500000      Asia    37.080  900.230000

In [ ]:
df

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2000    13500000      Asia    37.080  900.230000

[1705 rows x 6 columns]

In [ ]:
len(df.index)

1705

In [ ]:
df.loc[len(df.index) - 1] = ['India', 2004, 13500000, "Asia", 37.08, 900.23] #modifying a row using loc
df.tail()

country  year  population continent  life_exp     gdp_cap
1700  Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701  Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702  Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703  Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704     India  2004    13500000      Asia    37.080  900.230000

In [ ]:
#record --> row
#feature, attribute --> column

In [ ]:
df.head()

country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

In [ ]:
df.drop("country", axis=1)

year  population continent  life_exp     gdp_cap
0     1952     8425333      Asia    28.801  779.445314
1     1957     9240934      Asia    30.332  820.853030
2     1962    10267083      Asia    31.997  853.100710
3     1967    11537966      Asia    34.020  836.197138
4     1972    13079460      Asia    36.088  739.981106
...    ...         ...       ...       ...         ...
1700  1992    10704340    Africa    60.377  693.420786
1701  1997    11404948    Africa    46.809  792.449960
1702  2002    11926563    Africa    39.989  672.038623
1703  2007    12311143    Africa    43.487  469.709298
1704  2004    13500000      Asia    37.080  900.230000

[1705 rows x 5 columns]

In [ ]:
df.drop(3, axis=0)

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
5     Afghanistan  1977    14880372      Asia    38.438  786.113360
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2004    13500000      Asia    37.080  900.230000

[1704 rows x 6 columns]

In [ ]:
df.drop([1,2,4], axis=0)

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
5     Afghanistan  1977    14880372      Asia    38.438  786.113360
6     Afghanistan  1982    12881816      Asia    39.854  978.011439
7     Afghanistan  1987    13867957      Asia    40.822  852.395945
...           ...   ...         ...       ...       ...         ...
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2004    13500000      Asia    37.080  900.230000

[1702 rows x 6 columns]

In [ ]:
df.loc[len(df.index)] = ['India',2000,13500000,"asia",37.08,900.23]
df.loc[len(df.index)] = ['Sri Lanka',2022,130000000,"asia",80.00,500.00]
df.loc[len(df.index)] = ['Sri Lanka',2022,130000000,"asia",80.00,500.00]
df.loc[len(df.index)] = ['India',2000,13500000,"asia",80.00,900.23]
df.tail(10)

country  year  population continent  life_exp     gdp_cap
1699   Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700   Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701   Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702   Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703   Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704      India  2004    13500000      Asia    37.080  900.230000
1705      India  2000    13500000      asia    37.080  900.230000
1706  Sri Lanka  2022   130000000      asia    80.000  500.000000
1707  Sri Lanka  2022   130000000      asia    80.000  500.000000
1708      India  2000    13500000      asia    80.000  900.230000

In [ ]:
#working with duplicates

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1704    False
1705    False
1706    False
1707     True
1708    False
Length: 1709, dtype: bool

In [ ]:
df_dup = df.loc[df.duplicated()]

In [ ]:
df_dup

country  year  population continent  life_exp  gdp_cap
1707  Sri Lanka  2022   130000000      asia      80.0    500.0

In [ ]:
df.drop_duplicates()

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2004    13500000      Asia    37.080  900.230000
1705        India  2000    13500000      asia    37.080  900.230000
1706    Sri Lanka  2022   130000000      asia    80.000  500.000000
1708        India  2000    13500000      asia    80.000  900.230000

[1708 rows x 6 columns]

In [ ]:
df.drop_duplicates(keep="first")

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2004    13500000      Asia    37.080  900.230000
1705        India  2000    13500000      asia    37.080  900.230000
1706    Sri Lanka  2022   130000000      asia    80.000  500.000000
1708        India  2000    13500000      asia    80.000  900.230000

[1708 rows x 6 columns]

In [ ]:
df.drop_duplicates(keep="last")

country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298
1704        India  2004    13500000      Asia    37.080  900.230000
1705        India  2000    13500000      asia    37.080  900.230000
1707    Sri Lanka  2022   130000000      asia    80.000  500.000000
1708        India  2000    13500000      asia    80.000  900.230000

[1708 rows x 6 columns]

In [ ]:
df.sort_values(["life_exp"]) #df got sorted by life_exp in ascending order

country  year  population continent  life_exp       gdp_cap
1292            Rwanda  1992     7290203    Africa    23.599    737.068595
0          Afghanistan  1952     8425333      Asia    28.801    779.445314
552             Gambia  1952      284320    Africa    30.000    485.230659
36              Angola  1952     4232095    Africa    30.015   3520.610273
1344      Sierra Leone  1952     2143249    Africa    30.331    879.787736
...                ...   ...         ...       ...       ...           ...
1487       Switzerland  2007     7554661    Europe    81.701  37506.419070
695            Iceland  2007      301931    Europe    81.757  36180.789190
802              Japan  2002   127065841      Asia    82.000  28604.591900
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
803              Japan  2007   127467972      Asia    82.603  31656.068060

[1709 rows x 6 columns]

In [ ]:
df.sort_values(["year", "life_exp"])

country  year  population continent  life_exp       gdp_cap
0          Afghanistan  1952     8425333      Asia    28.801    779.445314
552             Gambia  1952      284320    Africa    30.000    485.230659
36              Angola  1952     4232095    Africa    30.015   3520.610273
1344      Sierra Leone  1952     2143249    Africa    30.331    879.787736
1032        Mozambique  1952     6446316    Africa    31.286    468.526038
...                ...   ...         ...       ...       ...           ...
695            Iceland  2007      301931    Europe    81.757  36180.789190
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
803              Japan  2007   127467972      Asia    82.603  31656.068060
1706         Sri Lanka  2022   130000000      asia    80.000    500.000000
1707         Sri Lanka  2022   130000000      asia    80.000    500.000000

[1709 rows x 6 columns]

In [ ]:
df.sort_values(["year", "life_exp"], ascending=False)

country  year  population continent  life_exp       gdp_cap
1706         Sri Lanka  2022   130000000      asia    80.000    500.000000
1707         Sri Lanka  2022   130000000      asia    80.000    500.000000
803              Japan  2007   127467972      Asia    82.603  31656.068060
671   Hong Kong, China  2007     6980412      Asia    82.208  39724.978670
695            Iceland  2007      301931    Europe    81.757  36180.789190
...                ...   ...         ...       ...       ...           ...
1032        Mozambique  1952     6446316    Africa    31.286    468.526038
1344      Sierra Leone  1952     2143249    Africa    30.331    879.787736
36              Angola  1952     4232095    Africa    30.015   3520.610273
552             Gambia  1952      284320    Africa    30.000    485.230659
0          Afghanistan  1952     8425333      Asia    28.801    779.445314

[1709 rows x 6 columns]

In [ ]:
df.sort_values(["year", "life_exp"], ascending=[False,True])

country  year  population continent  life_exp       gdp_cap
1706    Sri Lanka  2022   130000000      asia    80.000    500.000000
1707    Sri Lanka  2022   130000000      asia    80.000    500.000000
1463    Swaziland  2007     1133066    Africa    39.613   4513.480643
1043   Mozambique  2007    19951656    Africa    42.082    823.685621
1691       Zambia  2007    11746035    Africa    42.384   1271.211593
...           ...   ...         ...       ...       ...           ...
408       Denmark  1952     4334000    Europe    70.780   9692.385245
1464       Sweden  1952     7124673    Europe    71.860   8527.844662
1080  Netherlands  1952    10381988    Europe    72.130   8941.571858
684       Iceland  1952      147962    Europe    72.490   7267.688428
1140       Norway  1952     3327728    Europe    72.670  10095.421720

[1709 rows x 6 columns]

In [ ]:
users = pd.DataFrame({"userid":[1,2,3],"name":["Murali","Manogna","Taniksha"]})
users

userid      name
0       1    Murali
1       2   Manogna
2       3  Taniksha

In [ ]:
msgs = pd.DataFrame({"userid":[1,1,2,4],"msg":["hmm","acha","teek hai", "nice"]})
msgs

userid       msg
0       1       hmm
1       1      acha
2       2  teek hai
3       4      nice

In [ ]:
pd.concat([users,msgs], axis=0)

userid      name       msg
0       1    Murali       NaN
1       2   Manogna       NaN
2       3  Taniksha       NaN
0       1       NaN       hmm
1       1       NaN      acha
2       2       NaN  teek hai
3       4       NaN      nice

In [ ]:
pd.concat([users,msgs], axis=1)

userid      name  userid       msg
0     1.0    Murali       1       hmm
1     2.0   Manogna       1      acha
2     3.0  Taniksha       2  teek hai
3     NaN       NaN       4      nice

In [ ]:
pd.concat([users,msgs], axis=0,ignore_index=True)

userid      name       msg
0       1    Murali       NaN
1       2   Manogna       NaN
2       3  Taniksha       NaN
3       1       NaN       hmm
4       1       NaN      acha
5       2       NaN  teek hai
6       4       NaN      nice

In [ ]:
pd.concat([users,msgs], axis=1, join="inner")

userid      name  userid       msg
0       1    Murali       1       hmm
1       2   Manogna       1      acha
2       3  Taniksha       2  teek hai

In [ ]:
pd.concat([msgs,users], axis=1, join="outer")

userid       msg  userid      name
0       1       hmm     1.0    Murali
1       1      acha     2.0   Manogna
2       2  teek hai     3.0  Taniksha
3       4      nice     NaN       NaN

In [ ]:
# joins
# inner
# outer
# cross

In [ ]:
users

userid      name
0       1    Murali
1       2   Manogna
2       3  Taniksha

In [ ]:
msgs

userid       msg
0       1       hmm
1       1      acha
2       2  teek hai
3       4      nice

In [ ]:
users.merge(msgs, on="userid") # inner join

userid     name       msg
0       1   Murali       hmm
1       1   Murali      acha
2       2  Manogna  teek hai

In [ ]:
users.merge(msgs, on="userid", how="left")

userid      name       msg
0       1    Murali       hmm
1       1    Murali      acha
2       2   Manogna  teek hai
3       3  Taniksha       NaN

In [ ]:
users.rename(columns = {"userid" : "id"}, inplace = True)
users

id      name
0   1    Murali
1   2   Manogna
2   3  Taniksha

In [ ]:
users.merge(msgs, left_on="id", right_on="userid")

id     name  userid       msg
0   1   Murali       1       hmm
1   1   Murali       1      acha
2   2  Manogna       2  teek hai

In [ ]:
# IMDB data set --> Movies and Directors
import numpy as np
import pandas as pd
#movies = pd.read_csv("movies.csv")

In [ ]:
movies = pd.read_csv("movies.csv")

In [ ]:
movies

Unnamed: 0     id     budget  popularity     revenue  \
0              0  43597  237000000         150  2787965087   
1              1  43598  300000000         139   961000000   
2              2  43599  245000000         107   880674609   
3              3  43600  250000000         112  1084939099   
4              5  43602  258000000         115   890871626   
...          ...    ...        ...         ...         ...   
1460        4736  48363          0           3      321952   
1461        4743  48370      27000          19     3151130   
1462        4748  48375          0           7           0   
1463        4749  48376          0           3           0   
1464        4768  48395     220000          14     2040920   

                                         title  vote_average  vote_count  \
0                                       Avatar           7.2       11800   
1     Pirates of the Caribbean: At World's End           6.9        4500   
2                                      Spectre           6.3        4466   
3                        The Dark Knight Rises           7.6        9106   
4                                 Spider-Man 3           5.9        3576   
...                                        ...           ...         ...   
1460                            The Last Waltz           7.9          64   
1461                                    Clerks           7.4         755   
1462                                   Rampage           6.0         131   
1463                                   Slacker           6.4          77   
1464                               El Mariachi           6.6         238   

      director_id  year month       day  
0            4762  2009   Dec  Thursday  
1            4763  2007   May  Saturday  
2            4764  2015   Oct    Monday  
3            4765  2012   Jul    Monday  
4            4767  2007   May   Tuesday  
...           ...   ...   ...       ...  
1460         4809  1978   May    Monday  
1461         5369  1994   Sep   Tuesday  
1462         5148  2009   Aug    Friday  
1463         5535  1990   Jul    Friday  
1464         5097  1992   Sep    Friday  

[1465 rows x 12 columns]

In [ ]:
directors = pd.read_csv("directors.csv")
directors

Unnamed: 0      director_name    id gender
0              0      James Cameron  4762   Male
1              1     Gore Verbinski  4763   Male
2              2         Sam Mendes  4764   Male
3              3  Christopher Nolan  4765   Male
4              4     Andrew Stanton  4766   Male
...          ...                ...   ...    ...
2344        2344      Shane Carruth  7106   Male
2345        2345   Neill Dela Llana  7107    NaN
2346        2346        Scott Smith  7108    NaN
2347        2347        Daniel Hsia  7109   Male
2348        2348   Brian Herzlinger  7110   Male

[2349 rows x 4 columns]

In [ ]:
movies.head()

Unnamed: 0     id     budget  popularity     revenue  \
0           0  43597  237000000         150  2787965087   
1           1  43598  300000000         139   961000000   
2           2  43599  245000000         107   880674609   
3           3  43600  250000000         112  1084939099   
4           5  43602  258000000         115   890871626   

                                      title  vote_average  vote_count  \
0                                    Avatar           7.2       11800   
1  Pirates of the Caribbean: At World's End           6.9        4500   
2                                   Spectre           6.3        4466   
3                     The Dark Knight Rises           7.6        9106   
4                              Spider-Man 3           5.9        3576   

   director_id  year month       day  
0         4762  2009   Dec  Thursday  
1         4763  2007   May  Saturday  
2         4764  2015   Oct    Monday  
3         4765  2012   Jul    Monday  
4         4767  2007   May   Tuesday

In [ ]:
movies.drop(columns=["Unnamed: 0"], inplace=True)

In [ ]:
movies.head()

id     budget  popularity     revenue  \
0  43597  237000000         150  2787965087   
1  43598  300000000         139   961000000   
2  43599  245000000         107   880674609   
3  43600  250000000         112  1084939099   
4  43602  258000000         115   890871626   

                                      title  vote_average  vote_count  \
0                                    Avatar           7.2       11800   
1  Pirates of the Caribbean: At World's End           6.9        4500   
2                                   Spectre           6.3        4466   
3                     The Dark Knight Rises           7.6        9106   
4                              Spider-Man 3           5.9        3576   

   director_id  year month       day  
0         4762  2009   Dec  Thursday  
1         4763  2007   May  Saturday  
2         4764  2015   Oct    Monday  
3         4765  2012   Jul    Monday  
4         4767  2007   May   Tuesday

In [ ]:
directors.drop(columns=["Unnamed: 0"], inplace=True)

In [ ]:
directors.head()

director_name    id gender
0      James Cameron  4762   Male
1     Gore Verbinski  4763   Male
2         Sam Mendes  4764   Male
3  Christopher Nolan  4765   Male
4     Andrew Stanton  4766   Male

In [ ]:
movies.head()

id     budget  popularity     revenue  \
0  43597  237000000         150  2787965087   
1  43598  300000000         139   961000000   
2  43599  245000000         107   880674609   
3  43600  250000000         112  1084939099   
4  43602  258000000         115   890871626   

                                      title  vote_average  vote_count  \
0                                    Avatar           7.2       11800   
1  Pirates of the Caribbean: At World's End           6.9        4500   
2                                   Spectre           6.3        4466   
3                     The Dark Knight Rises           7.6        9106   
4                              Spider-Man 3           5.9        3576   

   director_id  year month       day  
0         4762  2009   Dec  Thursday  
1         4763  2007   May  Saturday  
2         4764  2015   Oct    Monday  
3         4765  2012   Jul    Monday  
4         4767  2007   May   Tuesday

In [ ]:
# Create a table that have the movie information along with the name and gender of the director who directed it.
#