<a href="https://colab.research.google.com/github/muralianamala/pythonlearning/blob/main/Scalar_DAV1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Day1 -> Python libraries: Numpy, Pandas, Matplotlib, Seaborn
Day2 -> Probability and Statistics
Day3 -> Hypothesis testing
'''

# **Numpy**

- import numpy as np
- %timeit - to calculate the execution time
- np.array(list) - converts list into np array
- ndim - gives dimensions
- shape - size of array in all dimensions
- np.arange - will create an array with a range of values
- np arrays can store only same datatypes
- Lists are storing references, but arrays are storing actual values in memory
- np.array(a,dtype="dataype") - which creates an array with similar datatype
- .astype(datatype) - converts an array into datatype
- indexing is similar to lists
-

In [ ]:
import numpy as np

In [ ]:
# Numerical in python - numpy means
# Speed comparision
# Numpy is useful wherever numerical operations needed

In [ ]:
l = list(range(10000000))
len(l)

10000000

In [ ]:
%timeit [i**2 for i in l]

3.59 s ± 570 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
b = np.array(l)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
#element-wise operation
#ndarray - n dimensional array

In [ ]:
%timeit b**2

27.1 ms ± 464 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [ ]:
a = np.array((5,7,3,6))
print(a**2)

[25 49  9 36]


In [ ]:
%timeit a**2

563 ns ± 5.97 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
b.ndim

1

In [ ]:
len(b)

10000000

In [ ]:
# it tells me the whole shape of array, if its multi dimensional
b.shape

(10000000,)

In [ ]:
#numpy are arrays, which they can store only same datatypes
#Lists are storing as references in memory
# Arrays are storing actual elements in memory

In [ ]:
c = list(range(1,10))
type(c)
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
c= np.arange(1,10)
print(c)

[1 2 3 4 5 6 7 8 9]


In [ ]:
type(c)

numpy.ndarray

In [ ]:
# stepping count can be a float in numpy
c = np.arange(1,5,0.5)
print(c)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [ ]:
len(c)

8

In [ ]:
a = [1,3,"MA"]
b = np.array(a)
print(b)
# converted everything to String , which same datatype

['1' '3' 'MA']


In [ ]:
a = [1,2,3,4]
b = np.array(a)
print(b)

[1 2 3 4]


In [ ]:
c = np.array(a, dtype="float")
print(c)

[1. 2. 3. 4.]


In [ ]:
a = [1,3,"MA"]
b = np.array(a,dtype="float")
print(b)

ValueError: ignored

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
a.ndim

1

In [ ]:
a.shape

(8,)

In [ ]:
b = a.astype("float")
print(b)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [ ]:
b= np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b= np.arange(1,12)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b= np.arange(1,12,2)
print(b)

[ 1  3  5  7  9 11]


In [ ]:
# indexing is same as list
b= np.arange(12)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
b[3]
b[::-2]

array([11,  9,  7,  5,  3,  1])

In [ ]:
b[-1]

11

In [ ]:
b[-2]

10

In [ ]:
b[-4]

8

In [ ]:
b

[8, 7, 6]

In [ ]:
b[1:5]

array([1, 2, 3, 4])

In [ ]:
b[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b[:2:-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3])

In [ ]:
b[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
b[:10:-1]

array([11])

In [ ]:
b[-5:11:]

array([ 7,  8,  9, 10])

In [ ]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [ ]:
arr[2:4] = 0
arr

array([0, 1, 0, 0, 4])

# **MULTIINDEXING**

- array[[,]]

In [ ]:
b = np.arange(1,15,2)
print(b)

[ 1  3  5  7  9 11 13]


In [ ]:
b[2]

5

In [ ]:
b[6]

13

In [ ]:
b[[2,6]]

array([ 5, 13])

In [ ]:
b[[5,2,4]]

array([11,  5,  9])

# **Fancy Indexing -> Masking**

- Masking is an intersting concept in numpy
- we can filter the records using this
- element wise operator will apply to each an every value within the array
-

In [ ]:
a = np.array([6,9,3,5,7,2,8,1])


In [ ]:
# element-wise operator
a < 6

array([False, False,  True,  True, False,  True, False,  True])

In [ ]:
a [ a<6 ]

array([3, 5, 2, 1])

In [ ]:
# Fliter all the even elements from a, using fancy indexing
a[ a%2==0 ]

array([6, 2, 8])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
b[::-2]

[6, 8]

In [ ]:
a[3:] = b[::-2]
print(a)

[1, 2, 3, 6, 8]


In [ ]:
a[ a%2 != 0]

array([9, 3, 5, 7, 1])

# **NPS Case Study**

In [ ]:
#NPS - Net promoter score
# NPS = %promoters - %Detractors

In [ ]:
'''
%promoters = #of promoters/total users
'''

In [ ]:
score = np.loadtxt("survey.txt", dtype = "int")

In [ ]:
p_rating = score[score > 8]
print(p_rating)

In [ ]:
no_promoters = len(p_rating)
print(no_promoters)

In [ ]:
total = len(score)

In [ ]:
perc_promoters = no_promoters*100/total
print(perc_promoters)

In [ ]:
d_rating = score[score < 7]
no_detractors = len(d_rating)
print(no_detractors)

In [ ]:
perc_detractors = no_detractors*100/total

In [ ]:
nps = perc_promoters - perc_detractors

In [ ]:
nps= np.round(nps,2)

# **NPS CASE Study**

In [ ]:
import numpy as np

In [ ]:
data = np.loadtxt("survey.txt", dtype="int")
total = len(data)

In [ ]:
promoters = data[data>8]
promoters

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [ ]:
#no_promoters = promoters.size
no_promoters = len(promoters)
perc_promoters = (no_promoters * 100)/total
print(perc_promoters)

52.18508997429306


In [ ]:
destructors = data[ data<7]
destructors

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [ ]:
no_dest = len(destructors)
print(no_dest)

332


In [ ]:
perc_dest = (no_dest * 100)/total
perc_dest

28.449014567266495

In [ ]:
nps = perc_promoters - perc_dest
print(np.round(nps,2))

23.74


# **ASSIGNMENT**

In [ ]:
a = np.arange(21,72,2)
print(a)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


In [ ]:
b = np.arange(22,71,2)
print(b)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

b= arr.astype(float)
print(b)

[10. 20. 30. 40. 50.]


In [ ]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
print(x)

[  5  -9  20  25   3  -5  16 -10  -8]


In [ ]:
a = np.array([100, 200, 300, 400])

b = np.array([300, 200, 100, 400])

print(a == b)

[False  True False  True]


In [ ]:
a = np.arange(5,35,3)
print(a)

[ 5  8 11 14 17 20 23 26 29 32]


In [ ]:
np.arange?

In [ ]:
import numpy as np

In [ ]:
x = [[0 1 2] [3 4 5] [6 7 8] [9 10 11]]

[3]


In [ ]:
print(True == 1)

True


# **DAY2**

Following are the topics we shall be covering in the upcoming class.

- Topic 1: Introduction
- Topic 2: Working with 2-D arrays (Matrices)
- Topic 3: Indexing and Slicing in 2D arrays
- Topic 4: Fancy Indexing on 2D arrays
- Topic 5: Aggregate Functions
- Topic 6: Logical Operations
- Topic 7: Logical Operations Contd
- Topic 8: Use Case- Fitbit data analysis
- Topic 9: Basic EDA
- Topic 10: Fitbit Solution
- Topic 11: Doubt Resolution

In [ ]:
import numpy as np

In [ ]:
a = np.array(range(16))

In [ ]:
a.shape

(16,)

In [ ]:
a.ndim

1

## **RESHAPE**

In [ ]:
b = a.reshape(8,2)

In [ ]:
print(b.shape)
print(a.shape)

(8, 2)
(16,)


In [ ]:
b.ndim

2

In [ ]:
#Reshape posisble only certain scenarios
# we can only reshape upto same numbers
c = a.reshape(4,5)
# 4,5 - 4*5 --> 20

ValueError: ignored

In [ ]:
d = a.reshape(8,-1)
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a = a.reshape(8,2)
print(a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
a.ndim

2

In [ ]:
len(a)

8

In [ ]:
len(a[0])

2

## **Transpose of a Matrix**

- a[row,col]

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
a[ a>4]

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
b= a.T

In [ ]:
b.shape

(4, 3)

In [ ]:
# nXm --> after transpose --> mXn

In [ ]:
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a = np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[0][1]

2

In [ ]:
a[1][2]

6

In [ ]:
a[1,2]

6

In [ ]:
a[2,0]

7

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[2,2]

9

In [ ]:
# Multi indexing in 2d numpy arrays
a = np.array([100,200,300,400,500,600])
a.ndim

1

In [ ]:
a[[2,3]]

array([300, 400])

In [ ]:
a[[2,3,4,1,2,2]]

array([300, 400, 500, 200, 300, 300])

In [ ]:
# multi indexing in 2-D
a = np.arange(9).reshape(3,3)

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a[[2,1],[1,2]]

array([7, 5])

In [ ]:
a[[2,0],[1,1]]

array([7, 1])

In [ ]:
# Task
# use multi indexing in 2D
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a[ [0,1,2],[0,1,2]]

array([0, 4, 8])

In [ ]:
#slicing
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a[:2,:] # slicing over rows
a[:,:2] # slicing over columns

array([[0, 1],
       [4, 5],
       [8, 9]])

In [ ]:
a[:,2:3]

array([[ 2],
       [ 6],
       [10]])

In [ ]:
a[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [ ]:
# Fancy indexing - Masking in 2D

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
a[ a < 6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1
a

array([-1,  1, -1,  3, -1,  5])

In [4]:
import numpy as np
a= np.arange(14).reshape(2,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [8]:
a[[1,1],[0,2]]

array([7, 9])

## **Aggregate Function**

- SUM
- MIN
- MAX
- COUNT
- AVG

In [9]:
a= np.arange(1,11)

In [10]:
np.sum(a)

55

In [11]:
np.mean(a)

5.5

In [12]:
np.min(a)

1

In [13]:
np.max(a)

10

In [14]:
# Aggregate functions in 2D

In [15]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 0 --> vertical (columns)
# 1 --> Horizontal (rows)

In [16]:
# row-wise sum [6,22,38]
np.sum(a,axis=1)

array([ 6, 22, 38])

In [17]:
#column-wise sum
np.sum(a,axis=0)

array([12, 15, 18, 21])

In [18]:
np.mean(a,axis=1)

array([1.5, 5.5, 9.5])

In [19]:
np.mean(a,axis=0)

array([4., 5., 6., 7.])

In [20]:
np.max(a,axis=1)

array([ 3,  7, 11])

In [21]:
np.max(a,axis=0)

array([ 8,  9, 10, 11])

In [22]:
np.min(a,axis=1)

array([0, 4, 8])

In [23]:
np.min(a,axis=0)

array([0, 1, 2, 3])

## **Logical Operations**

- np.all(logic) - it checks all within an array apply and logic
- np.any(logic) - OR logic

In [28]:
a = np.array([5,7,2,8,1])
a

array([5, 7, 2, 8, 1])

In [25]:
a < 3

array([False, False,  True, False,  True])

In [26]:
a >3

array([ True,  True, False,  True, False])

In [29]:
#np.all() and np.any()
np.all(a<3)

False

In [30]:
np.any(a<3)

True

In [31]:
a = np.array([0,2,3])
b = np.array([1,3,5])
a>=b

array([False, False, False])

In [32]:
# if lengths are different, cant apply element-wise operation
print(a+b)

[1 5 8]


In [35]:
arr = np.array([-3,4,27,34,-2,0,-45,-11,4,0])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [34]:
arr [arr < 0] = -1
arr [arr > 0] = 1
arr

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [ ]:
# WHERE()
# np.where(condition,true(value),false(value)])

In [38]:
arr = np.where(arr>0,-1,1)
arr

array([ 1, -1, -1, -1,  1,  1,  1,  1, -1,  1])

In [39]:
arr = np.array([-3,4,27,34,-2,0,-45,-11,4,0])
print(np.where(arr))
# HW -- understand this

(array([0, 1, 2, 3, 4, 6, 7, 8]),)


## **CASE STUDY**

In [ ]:
# HW --> Try to compare the avg steps the user takes when mood is happy and when mood is Sad